<?php

/*

mGenerator ver. 0.1.0 - automat tworzenia do podstron
ostatnia modyfikacja: 2010-06-22
copyright 2010 Marcin Kowol
marcin@kowol.pl

This file is part of mGenerator.

mGenerator is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

mGenerator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with mGenerator; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

Ten plik jest czê¶ci± mGenerator.

mGenerator jest wolnym oprogramowaniem; mo¿esz go rozprowadzaæ dalej
i/lub modyfikowaæ na warunkach Powszechnej Licencji Publicznej GNU,
wydanej przez Fundacjê Wolnego Oprogramowania - wed³ug wersji 2 tej
Licencji lub (wed³ug twojego wyboru) której¶ z pó¼niejszych wersji.

Niniejszy program rozpowszechniany jest z nadziej±, i¿ bêdzie on
u¿yteczny - jednak BEZ JAKIEJKOLWIEK GWARANCJI, nawet domy¶lnej
gwarancji PRZYDATNO¦CI HANDLOWEJ albo PRZYDATNO¦CI DO OKRE¦LONYCH
ZASTOSOWAÑ. W celu uzyskania bli¿szych informacji siêgnij do
Powszechnej Licencji Publicznej GNU.

Z pewno¶ci± wraz z niniejszym programem otrzyma³e¶ te¿ egzemplarz
Powszechnej Licencji Publicznej GNU (GNU General Public License);
je¶li nie - napisz do Free Software Foundation, Inc., 59 Temple
Place, Fifth Floor, Boston, MA  02110-1301  USA


*/

if ($_GET['kontrolka'] == 'comamzrobic') {

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" />
	<title>mGenerator ver. 0.1.0</title>
  <meta name="robots" content="none" >
	
</head>

<body>
		
<ol>
<li><a href="paczka.zip">¦ci±gnij wygenerowan± paczkê</a></li>
<li>Rozpakuj ¶ci±gniêt± paczkê "paczka.zip".</li>
<li>Je¶li masz ju¿ mapê strony, to skopiuj z niej rêcznie linki do pliku "sitemap.xml", który rozpakowa³e¶ z paczki.</li>
<li>Skopiuj wszystkie pliki z paczki do g³ównego katalogu witryny (tam gdzie jest index).</li>
<li>Kliknij tutaj: <a href="http://<?php echo $_GET['domena']; ?>/ping.php"><?php echo $_GET['domena']; ?>/ping.php</a></li>
</ol>

</body>
</html>

<?php

} elseif (!(isset($_GET['domena'])))	{

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" />
	<title>mGenerator ver. 0.1.0</title>
  <meta name="robots" content="none" >
	
</head>

<body>
		
<div class="pudlo">
  <form enctype="application/x-www-form-urlencoded" action="mgenerator.php" accept-charset="iso-8859-2" method="get">
    <div class="row">
      <span class="label">g³ówny adres domeny: </span><span
class="formw"><input type="text" name="domena" size="35" /></span> bez "http://", istotne jest czy z www czy bez www
    </div>
    <div class="row">
      <span class="label">pozycjonowana fraza: </span><span
class="formw"><input type="text" name="fraza" size="50" />
    </div>
    <div class="row">
      <span class="label">i jej alias (do linków): </span><span
class="formw"><input type="text" name="alias" size="50" /> (je¶li nic nie wpiszesz, bêdzie taki jak podana fraza - usuñ wiêc polskie znaki, spacje itp.)
    </div>
		<div class="row">
		<input type="submit" value="wczytaj index" /> <input type="submit" value="nie wczytuj, id¼ dalej" />
		</div>
	</form>
</div>

</body>
</html>

<?php

} elseif (!(isset($_GET['link']))) {

	if ($_GET['submit'] = 'wczytaj index') {
	
		function curl_get_data($url, $datacenter, $dst_path = null, $timeout = null) {
			$ch  = curl_init ("http://" . $datacenter . $url);
			if (empty($timeout)) {
				$timeout = 0;
			}    
			curl_setopt($ch, CURLOPT_TIMEOUT, $timeout);
			$headers = array(
				"GET " . $url . " HTTP/1.1",
				"Host: " . $datacenter,
				"User-Agent: " . $user_agents[rand(0, count($user_agents)-1)],
				"Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"Accept-Language: pl,en-us;q=0.7,en;q=0.3",
				"Accept-Encoding: gzip,deflate",
				"Accept-Charset: ISO-8859-2,utf-8;q=0.7,*;q=0.7",
				"Keep-Alive: 300",
				"Connection: keep-alive",
				"Referer: http://www.google.com/"
			);
			curl_setopt($ch, CURLOPT_HEADER, $headers);
			if (!empty($dst_path))
			{
				curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
				curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
			}
			$res = curl_exec ($ch) ;
			curl_close ($ch) ;
			if (is_string($dst_path) and  ($dst_path == 'string'))
			{
				return $res;
			}
			if (!empty($dst_path))
			{
				$fh = fopen($dst_path, 'w+');
				fwrite($fh, $res);
				fclose($fh);         
			}
		}
	
	}

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml2/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pl">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" />
	<title>mGenerator ver. 0.1.0 </title>
  <meta name="robots" content="none" >
	
</head>

<body>
		
<div class="pudlo">
  <form enctype="application/x-www-form-urlencoded" action="mgenerator.php" accept-charset="iso-8859-2" method="get">
    <div class="row">
			<input type="hidden" name="domena" value="<?php echo $_GET['domena']; ?>" />
			<input type="hidden" name="fraza" value="<?php $fraza = $_GET['fraza']; echo $fraza; ?>" />
			<input type="hidden" name="alias" value="<?php $alias = $_GET['alias']; if ($alias == '') { $alias = $fraza; } echo $alias; ?>" />
      <span class="label">nazwa domeny: <span style="color:red;"><?php echo $_GET['domena']; ?></span>, pozycjonowana fraza: <span style="color:red;"><?php echo $_GET['fraza']; ?></span> i jej alias: <span style="color:red;"><?php echo $alias; ?></span></span>
    </div>
    <div class="row">
      <span class="label">ilo¶æ linków wewnêtrznych w stopce: </span><span
class="formw"><input type="text" name="ilosc" size="2" value="5" /></span>
    </div>
    <div class="row">
      <span class="label">templatka linka: </span><span
class="formw"><input type="text" name="link" size="100" value="<span><a href=&#8243;{link}&#8243; title=&#8243;{fraza} {miasto}&#8243;>{fraza} {miasto}</a></span> :: " />(je¶li chcesz go ostylowaæ, je¶li nie - pozostaw liniê bez zmian)
    </div>
		<hr />.htaccess(je¶li masz ju¿ plik .htaccess na serwerze, dodaj tutaj jego zawarto¶æ):
    <div class="row">
      <span class="label"></span><span class="formw">
		<textarea name="htaccess" cols="125" rows="3" />RewriteEngine On

RewriteRule ^<?php echo $alias; ?>_(.+)_(.+)\.php$ ./sprzeg.php?wojewodztwo=$1&miasto=$2 [L,QSA]
</textarea>
    </div>
    <div class="row">
      <span class="label">Zamieniæ automatycznie wszystkie wyst±pienia <?php echo $_GET['fraza']; ?> na <?php echo $_GET['fraza']; ?> plus miasto: </span><span
class="formw"><input type="checkbox" name="zamiana" value="tak"></span>
    </div>
		<hr>Poni¿ej przygotuj templatkê wed³ug uznania, wykorzystuj±c: <span style="color:blue;">{miasto}</span> - zostanie zast±pione nazw± miasta oraz <span style="color:blue;">{linki}</span> - tu zostan± wstawione wewnêtrzne linki do innych podstron miast. Nie zapomnij usun±æ nag³ówka, je¶li pobiera³e¶ indeks automatycznie.
		<div class="row">
		<textarea name="templatka" cols="125" rows="17">
<?php 
	curl_get_data('/', $_GET['domena']);
?>
		</textarea>
		</div>
		<div class="row">
		<input type="submit" value="generuj paczkê" />
		</div>
	</form>
</div>

</body>
</html>

<?php 

} else {

	$wojewodztwa = array(
		'dolnoslaskie',
		'kujawskopomorskie',
		'lodzkie',
		'lubelskie',
		'lubuskie',
		'malopolskie',
		'mazowieckie',
		'opolskie',
		'podkarpackie',
		'podlaskie',
		'pomorskie',
		'slaskie',
		'swietokrzyskie',
		'warminskomazurskie',
		'wielkopolskie',
		'zachodniopomorskie'
		);

	$dolnoslaskie = array(
		'dolnoslaskie',
		'Wroc³aw',
		'Bardo',
		'Bia³o³êka',
		'Bia³y Ko¶ció³',
		'Bielany Wroc³awskie',
		'Bielawa',
		'Bierkowice',
		'Bierutów',
		'Bogatynia',
		'Boguszów Gorce',
		'Boles³awiec ¦l±ski',
		'Bolków',
		'Borek Strzeliñski',
		'Borowa Ole¶nicka',
		'Borów',
		'Bo¿ków',
		'Braszowice',
		'Brochocin',
		'Brodziszów',
		'Brzeg Dolny',
		'Brzezia £±ka',
		'Budzów',
		'Budzów k. Z±bkowic ¦l±skich',
		'Bukowice',
		'Bukówek',
		'Bystrzyca',
		'Bystrzyca k. O³awy',
		'Bystrzyca K³odzka',
		'Che³msko ¦l±skie',
		'Chocianowiec',
		'Chocianów',
		'Chojnów',
		'Chrz±stawa Wielka',
		'Ciep³owody',
		'Cieszków',
		'Czarny Bór',
		'Czernica',
		'Czernica k. Wroc³awia',
		'Czernina',
		'Czerwona Woda',
		'D³ugo³êka',
		'D³ugopole Zdrój',
		'D³u¿yna Dolna',
		'Dobromierz',
		'Dobroszyce',
		'Dobroszyce k. Ole¶nicy ¦l±skiej',
		'Domanice',
		'Domanice k. ¦widnicy ¦l±skiej',
		'Domaniów',
		'Domaszków',
		'Duszniki Zdrój',
		'Dziadowa K³oda',
		'Dzia³oszyn',
		'Dzia³oszyn k. Zgorzelca',
		'Dzier¿oniów',
		'Gaworzyce',
		'G±dkowice',
		'Giebu³tów',
		'G³ogów',
		'G³uszyca',
		'Gniechowice',
		'Gocza³ków',
		'Gorzanów',
		'Gos³awice',
		'Gos³awice k. ¦rody ¦l±skiej',
		'Goszcz',
		'Goszcz k. Sycowa',
		'Go¶ciszów',
		'Góra ¦l±ska',
		'Grabowno Wielkie',
		'Grêbocice',
		'Grodziszcze',
		'Gromadka',
		'Gryfów ¦l±ski',
		'Henryków',
		'Henryków k. Z±bkowic ¦l±skich',
		'Idzików',
		'Iwiny',
		'Iwiny k. Boles³awca ¦l±skiego',
		'Janowice Wielkie',
		'Jaroszów',
		'Jawor',
		'Jaworzyna ¦l±ska',
		'Jedlina Zdrój',
		'Jeg³owa',
		'Jelcz-Laskowice',
		'Jelenia Góra',
		'Jemielno',
		'Jerzmanowa',
		'Jerzmanowa k. G³ogowa',
		'Je¿ów Sudecki',
		'Jordanów ¦l±ski',
		'Jugowice',
		'Kaczorów',
		'Kamieniec Wroc³awski',
		'Kamieniec Z±bkowicki',
		'Kamienna Góra',
		'Karczyce',
		'Karpacz',
		'K±ty Wroc³awskie',
		'Kie³czów',
		'K³odzko',
		'Kobierzyce',
		'Kostom³oty',
		'Kotla',
		'Kowary',
		'Krosnowice',
		'Kro¶nice',
		'Krotoszyce',
		'Krzelów',
		'Krzeszów Kamiennogórski',
		'Ksiêginice',
		'Ksiêginice k. ¦rody ¦l±skiej',
		'Kudowa Zdrój',
		'Kunice Legnickie',
		'Kuropatnik',
		'Ku¼nica Czeszycka',
		'Laski',
		'Laski k. Z±bkowic ¦l±skich',
		'L±dek Zdrój',
		'Legnica',
		'Legnickie Pole',
		'Leszczyniec',
		'Le¶na',
		'Le¶na k. Lubania ¦l±skiego',
		'Lewin K³odzki',
		'Lipa Jaworska',
		'Lubañ ¦l±ski',
		'Lubawka',
		'Lubi±¿',
		'Lubin',
		'Lubomierz',
		'Luboszyce',
		'Ludwikowice K³odzkie',
		'Lutynia',
		'Lwówek ¦l±ski',
		'£agiewniki',
		'£agiewniki k. Dzier¿oniowa',
		'£ozina',
		'£uczyna',
		'Malczyce',
		'Marcinkowice',
		'Marcinowice',
		'Marciszów',
		'Mêcinka',
		'Mieroszów',
		'Mietków',
		'Miêdzybórz',
		'Miêdzygórze',
		'Miêdzylesie',
		'Miêdzylesie k. Bystrzycy K³odzkiej',
		'Miêkinia',
		'Milicz',
		'Mi³kowice',
		'Mi³ków',
		'Mi³oradzice',
		'Minkowice O³awskie',
		'Mirków',
		'Mirsk',
		'Miszkowice',
		'Mrozów',
		'M¶ciwojów',
		'Mys³akowice',
		'Niechlów',
		'Nielubia',
		'Niemcza',
		'Niwnice',
		'Nowa Ruda',
		'Nowogrodziec',
		'Oborniki ¦l±skie',
		'Okmiany',
		'Okrzeszyn',
		'Ole¶nica ¦l±ska',
		'Olszanica',
		'Olszanica k. Z³otoryi',
		'Olszyna',
		'O³awa',
		'O³drzychowice K³odzkie',
		'Osiecznica',
		'Osiecznica k. Boles³awca ¦l±skiego',
		'Osiek',
		'Osiek k. ¦rody ¦l±skiej',
		'Osola',
		'Ostroszowice',
		'Parszowice',
		'Pastuchów',
		'Paszowice',
		'Pêgów',
		'Piechowice',
		'Pielgrzymka',
		'Pieñsk',
		'Pieszyce',
		'Pi³awa Górna',
		'Platerówka',
		'P³awna',
		'Pobiedna',
		'Podgórzyn',
		'Polanica Zdrój',
		'Polkowice',
		'Pomocne',
		'Poniatowice',
		'Prochowice',
		'Prusice',
		'Prusy',
		'Przedborowa',
		'Przedmo¶cie',
		'Przemków',
		'Przesieka',
		'Przeworno',
		'Przy³êk',
		'Przy³êk k. Z±bkowic ¦l±skich',
		'Raciborowice Górne',
		'Radków K³odzki',
		'Radomierzyce',
		'Radwanice',
		'Radwanice k. Wroc³awia',
		'Raszówka',
		'Rogów',
		'Rokitki',
		'Roztoka',
		'Rudna',
		'Ruja',
		'Ruszów',
		'Sarby',
		'Sêdzis³aw',
		'Siciny',
		'Siechnice',
		'Siekierczyn',
		'Sieniawka',
		'Sieniawka k. Bogatyni',
		'Skokowa',
		'Smolec',
		'Sobótka',
		'Sobótka k. Wroc³awia',
		'Soko³owice',
		'Soko³owsko',
		'Sosnówka',
		'Sosnówka k. Jeleniej Góry',
		'Srebrna Góra',
		'Stara Kamienica',
		'Stare Bogaczowice',
		'Stary Waliszów',
		'Stary Wielis³aw',
		'Stoszowice',
		'Stronie ¦l±skie',
		'Strzegom',
		'Strzelin',
		'Sulików',
		'Su³ów',
		'Syców',
		'Szalejów Górny',
		'Szczawno Zdrój',
		'Szczepanów',
		'Szczytna K³odzka',
		'Szklarska Porêba',
		'¦ciêgny',
		'¦cinawa',
		'¦cinawa k. Wo³owa',
		'¦cinawka ¦rednia',
		'¦roda ¦l±ska',
		'¦widnica Polska',
		'¦widnica ¦l±ska',
		'¦wiebodzice',
		'¦wieradów Zdrój',
		'¦wierzawa',
		'¦wiêta Katarzyna',
		'¦wiêtoszów',
		'T³umaczów',
		'Tomaszów Górny',
		'Trójca',
		'Trzebieñ',
		'Trzebieszowice',
		'Trzebnica',
		'Twardogóra',
		'Tymowa k. Wo³owa',
		'Tyniec Ma³y',
		'Uciechów',
		'Udanin',
		'Ujazd Górny',
		'Uje¼dziec Wielki',
		'Unis³aw ¦l±ski',
		'Uraz',
		'Wabienice',
		'Walim',
		'Wa³brzych',
		'Warta Boles³awiecka',
		'W±dro¿e Wielkie',
		'W±sosz',
		'W±sosz k. Góry ¦l±skiej',
		'Wêgliniec',
		'Wêgry',
		'Wi±zów',
		'Wierzbno',
		'Wierzbno k. O³awy',
		'Wilkanów',
		'Wilków',
		'Wilków k. Z³otoryi',
		'Wiñsko',
		'Wiry',
		'Wisznia Ma³a',
		'Wleñ',
		'Wojbórz',
		'Wojcieszów',
		'Wolibórz',
		'Wolibórz k. K³odzka',
		'Wo³ów',
		'Wroniniec',
		'Wykroty',
		'Zagrodno',
		'Zarêba Górna',
		'Zawidów',
		'Zawonia',
		'Z±bkowice ¦l±skie',
		'Zebrzydowa',
		'Zgorzelec',
		'Zielenice Strzeliñskie',
		'Ziêbice',
		'Z³otoryja',
		'Z³oty Stok',
		'¯arów',
		'¯arska Wie¶',
		'¯elazno',
		'¯erniki',
		'¯erniki Wroc³awskie',
		'¯erniki Wroc³awskie Ag.',
		'¯migród',
		'¯órawina',
		'¯ukowice'
	);

	$kujawskopomorskie = array(
		'kujawskopomorskie',
		'Bydgoszcz',
		'Aleksandrów Kujawski',
		'Barcin',
		'Bartniczka',
		'Baruchowo',
		'B±dkowo',
		'Bia³e B³ota',
		'Biskupin',
		'B³enna',
		'Bobrowniki',
		'Bobrowniki n. Wis³±',
		'Bobrowo',
		'Boniewo',
		'Brodnica',
		'Brze¶æ Kujawski',
		'Brze¼no',
		'Brze¼no k. Lipna',
		'Brzoza',
		'Brzozie',
		'Brzuze',
		'Bukowiec Pomorski',
		'Buszkowo',
		'Buszkowo k. Koronowa',
		'Bycz',
		'Bys³aw',
		'Bytoñ',
		'Bytoñ k. Radziejowa',
		'Cekcyn',
		'Chalin',
		'Che³mce',
		'Che³mce k. Inowroc³awia',
		'Che³mno',
		'Che³m¿a',
		'Choceñ',
		'Chodecz',
		'Chrostkowo',
		'Chrostkowo k. Lipna',
		'Ciechocin',
		'Ciechocinek',
		'Cierpice',
		'Czar¿e',
		'Czerniewice',
		'Czerniewice k. W³oc³awka',
		'Czernikowo',
		'D±browa Biskupia',
		'D±browa Che³miñska',
		'D±browa',
		'D±browa k. Mogilna',
		'D±brówka',
		'D±brówka k. Sêpólna Krajeñskiego',
		'Dêbowa £±ka',
		'Dobrcz',
		'Dobre Kujawskie',
		'Dobrzejewice',
		'Dobrzyñ',
		'Dobrzyñ n. Wis³±',
		'Dragacz',
		'Drzycim',
		'Dzia³yñ Mazowiecki',
		'Dziewierzewo',
		'Fabianki',
		'G±sawa',
		'Gêbice',
		'Gêbice k. Mogilna',
		'Gniewkowo',
		'Golub-Dobrzyñ',
		'Gorzyce',
		'Gorzyce k. ¯nina',
		'Gostycyn',
		'Gostycyn k. Tucholi',
		'Go¶cieszyn',
		'Go¶cieszyn k. ¯nina',
		'Górna Grupa',
		'Górzno',
		'Górzno k. Brodnicy',
		'Grêbocin',
		'Grochowalsk',
		'Gromadno',
		'Gromadno k. Szubina',
		'Gruczno',
		'Grudzi±dz',
		'Grupa',
		'Gruta',
		'Inowroc³aw',
		'Iwiec',
		'Iwiec k. Tucholi',
		'Izbica Kujawska',
		'Jab³onowo Pomorskie',
		'Jadowniki',
		'Jadowniki k. ¯nina',
		'Jaksice',
		'Janikowo',
		'Janowiec Wielkopolski',
		'Jastrzêbie',
		'Jastrzêbie k. Brodnic',
		'Jeziora Wielkie',
		'Je¿ewo',
		'Je¿ewo k. Laskowic',
		'Kamieñ Krajeñski',
		'Kcynia',
		'Kêsowo',
		'Kijewo Królewskie',
		'Kikó³',
		'Koneck',
		'Koronowo',
		'Kotomierz',
		'Kowal',
		'Kowalewo Pomorskie',
		'Królikowo',
		'Kruszwica',
		'Kruszyn',
		'Kruszyny',
		'Ksi±¿ki',
		'Kwieciszewo',
		'Laski Wielkie',
		'Laskowice',
		'Laskowice k. ¦wiecia',
		'Legb±d',
		'Lipno',
		'Lisewo',
		'Lisewo k. Che³mna',
		'Lisnowo',
		'Lniano',
		'Lubanie',
		'Lubanie k. Nieszawy',
		'Lubicz',
		'Lubieñ Kujawski',
		'Lubiewo',
		'Lubraniec',
		'Lutowo',
		'Lutówko',
		'£abiszyn',
		'£asin',
		'£ob¿enica',
		'£ochowo',
		'£owiczek',
		'£ubianka',
		'£ysomice',
		'Maksymilianowo',
		'Ma³e Gacno',
		'Ma³ki',
		'Mazowsze',
		'M±kowarsko',
		'Me³no',
		'Minikowo',
		'Mogilno',
		'Mokowo',
		'Mrocza',
		'Nak³o',
		'Nak³o n. Noteci±',
		'Niemcz',
		'Nieszawa',
		'Nie¿ywiêæ',
		'Nowa Wie¶',
		'Nowa Wie¶ k. Piotrkowa Kujawskiego',
		'Nowa Wie¶ Królewska',
		'Nowa Wie¶ Królewska na Pomorzu',
		'Nowa Wie¶ Wielka',
		'Nowe',
		'Nowe k. ¦wiecia',
		'Obrowo',
		'Okalewo',
		'Osie',
		'Osiek',
		'Osiek n. Wis³±',
		'Osiek Rypiñski',
		'Osielsko',
		'Osiêciny',
		'Osówka',
		'Ostrowite Rypiñskie',
		'Ostrowo Mogileñskie',
		'Pako¶æ',
		'Papowo Biskupie',
		'Piechcin',
		'Piotrków Kujawski',
		'Plesewo',
		'P³u¿nica',
		'Podobowice',
		'Podwiesk',
		'Pokrzydowo',
		'Potulice',
		'Prêczki',
		'Pruszcz',
		'Pruszcz k. Bydgoszczy',
		'Pruszcz-Bagienica',
		'Przyjezierze',
		'Raci±¿',
		'Raci±¿ k. Tucholi',
		'Raci±¿ek',
		'Radomin',
		'Radziejów',
		'Radziki Du¿e',
		'Radzyñ Che³miñski',
		'Rogowo',
		'Rogowo k. Rypina',
		'Rogowo ¯niñskie',
		'Rogó¼no',
		'Rogó¼no k. Grudzi±dza',
		'Rojewo',
		'Runowo Krajeñskie',
		'Rynarzewo',
		'Ryñsk',
		'Rypin',
		'Rzêczkowo',
		'Sadki',
		'Sad³owo',
		'Serock Pomorski',
		'Sêdzin',
		'Sêpólno Krajeñskie',
		'Sicienko',
		'Siniarzewo',
		'Sitno',
		'Skêpe',
		'Skrwilno',
		'S³u¿ewo',
		'Smólnik',
		'Solec Kujawski',
		'So¶no',
		'Stêpowo',
		'Stolno',
		'Straszewo',
		'Straszewo k. Aleksandrowa Kujawskiego',
		'Strzelno',
		'Sucha na Pomorzu',
		'Sypniewo',
		'Sypniewo k. Wiêcborka',
		'Szczepanowo',
		'Szczepanowo k. Barcina',
		'Szubin',
		'¦lesin',
		'¦lesin k. Nak³a',
		'¦lesin k. Nak³a n. Noteci±',
		'¦liwice',
		'¦wiecie',
		'¦wiecie n. Os±',
		'¦wiecie n. Wis³±',
		'¦wiedziebnia',
		'¦wiekatowo',
		'T³uchowo',
		'Topólka',
		'Toruñ',
		'Trzeciewiec',
		'Tuchola',
		'Tuczno',
		'Tuczno k. Inowroc³awia',
		'Tur',
		'Ugoszcz k. Rypina',
		'Unis³aw',
		'Urszulewo',
		'Waganiec',
		'Wa³dowo',
		'Wa³dowo k. Sêpólna Krajeñskiego',
		'Warlubie',
		'W±brze¼no',
		'W±pielsk',
		'W±welno',
		'Wielgie',
		'Wielgie k. Lipna',
		'Wielka Klonia',
		'Wieniec',
		'Wierzchos³awice',
		'Wierzchos³awice k. Inowroc³awia',
		'Wierzchucin Królewski',
		'Wiêcbork',
		'Witos³aw',
		'Witowo',
		'Witowo k. Aleksandrowa Kujawskiego',
		'W³oc³awek',
		'W³ostowo',
		'Wójcin',
		'Wójcin k. Strzelna',
		'Wrocki',
		'Wronowy',
		'Wtelno',
		'Zaduszniki',
		'Zakrzewo',
		'Zalesie',
		'Zalesie k. Szubina',
		'Zawiszyn',
		'Zbiczno',
		'Zbójno',
		'Zbójno k. Rypina',
		'Zg³owi±czka',
		'Z³awie¶ Wielka',
		'Z³otniki Kujawskie',
		'Z³otoria',
		'Z³otoria n. Wis³±',
		'¯erniki',
		'¯nin'
	);
	$lodzkie = array(
		'lodzkie',
		'£ód¼',
		'Aleksandrów',
		'Aleksandrów £ódzki',
		'Andrespol',
		'Bedlno',
		'Bednary',
		'Be³chatów',
		'Be³chów',
		'Bêdków',
		'Bia³a',
		'Bia³a k. Zgierza',
		'Bia³a Rawska',
		'Bia³aczów',
		'Bielawy',
		'B³aszki',
		'B³onie k. £êczycy',
		'Boles³awiec',
		'Bolimów',
		'Bratoszewice',
		'Br±szewice',
		'Brójce',
		'Brzeziny',
		'Brze¼nio',
		'Buczek',
		'Budziszewice',
		'Burzenin',
		'Byszew k. Witoni',
		'Ch±¶no',
		'Ciel±dz',
		'Czarnocin',
		'Czarno¿y³y',
		'Czastary',
		'Czerniewice',
		'Dalików',
		'Daszyna',
		'D±browice',
		'Dêbowa Góra',
		'D³utów',
		'Dmosin',
		'Dobroñ',
		'Dobryszyce',
		'Dobrzelin',
		'Domaniewice',
		'Dru¿bice',
		'Drzewica',
		'Dzia³oszyn',
		'Galewice',
		'Ga³kówek',
		'Gidle',
		'G³owno',
		'G³uchów',
		'Godzianów',
		'Gomunice',
		'Gorzkowice',
		'Goszczanów',
		'Góra ¦wiêtej Ma³gorzaty',
		'Grabica',
		'Grabów',
		'Grotniki',
		'Inow³ódz',
		'Je¿ów',
		'Kamieñsk',
		'Kaszewy Ko¶cielne',
		'Kie³czyg³ów',
		'Kiernozia',
		'Kleszczów',
		'Klonowa',
		'Kluki',
		'Kobiele Wielkie',
		'Kocierzew',
		'Kodr±b',
		'Koluszki',
		'Konopnica',
		'Konstantynów £ódzki',
		'Kowiesy',
		'Kro¶niewice',
		'Krzy¿anów',
		'Ksawerów',
		'Kutno',
		'Le¼nica Ma³a',
		'Le¼nica Wielka',
		'Lgota Wielka',
		'Lipce Reymontowskie',
		'Lubania',
		'Lubochnia',
		'Lutomiersk',
		'Lututów',
		'£adzice',
		'£aniêta',
		'£ask',
		'£êczyca',
		'£êczyca',
		'£êki Szlacheckie',
		'£owicz',
		'£ubnice',
		'£yszkowice',
		'Maków',
		'Mas³owice',
		'Mazew',
		'Miros³awice k. ¯ychlinka',
		'Mnich k. Kutna',
		'Mniszków',
		'Mokrsko',
		'Moszczenica',
		'Nieborów',
		'Niemys³ów',
		'Nowa Brze¼nica',
		'Nowe k. Kutna',
		'Nowy Kawêczyn',
		'Opoczno',
		'Oporów',
		'Osjaków',
		'Ostrowy',
		'Ostrówek',
		'Ozorków',
		'Pabianice',
		'Pajêczno',
		'Parady¿',
		'Parzêczew',
		'P±tnów',
		'Pêczniew',
		'Pi±tek',
		'Piotrków Trybunalski',
		'Plecka D±browa',
		'Poddêbice',
		'Po¶wiêtne',
		'Przedbórz',
		'Radomsko',
		'Rawa Mazowiecka',
		'R±bieñ',
		'Regnów',
		'Rêczno',
		'Rogowiec',
		'Rogów',
		'Rokiciny',
		'Rozprza',
		'Rusiec',
		'Rz±¶nia',
		'Rzeczyca',
		'Rzgów',
		'Sadkowice',
		'Sêdziejowice',
		'Siedlec k. £êczycy',
		'Siemkowice',
		'Sieradz',
		'Skierniewice',
		'Skomlin',
		'S³awno',
		'S³upia',
		'Smardzew',
		'Smardzewice',
		'Sobótka k. £êczycy',
		'Sokolniki',
		'Stryków',
		'Strzelce',
		'Strzelce Wielkie',
		'Sulejów',
		'Sulmierzyce',
		'Szadek',
		'Szczerców',
		'¦leszyn',
		'¦winice Warckie',
		'Tomaszów Mazowiecki',
		'Tuszyn',
		'Ujazd',
		'Uniejów',
		'Warta',
		'Wartkowice',
		'Widawa',
		'Wielgom³yny',
		'Wieluñ',
		'Wieruszów',
		'Wierzchlas',
		'Witonia',
		'Wodzierady',
		'Wola Krzysztoporska',
		'Wolbórz',
		'Wróblew',
		'Wysoka Wielka',
		'Zadzim',
		'Za³usin',
		'Zapolice',
		'Zduny',
		'Zduñska Wola',
		'Zelów',
		'Zgierz',
		'Z³oczew',
		'¯arnów',
		'¯elechlinek',
		'¯ychlin'
	);
	$lubelskie = array(
		'lubelskie',
		'Lublin',
		'Abramów',
		'Adamów',
		'Aleksandrów',
		'Annopol',
		'Baranów',
		'Batorz',
		'Bedlno',
		'Be³¿ec',
		'Be³¿yce',
		'Bia³a Podlaska',
		'Bia³opole',
		'Bi³goraj',
		'Biszcza',
		'Bodaczów',
		'Boiska Stare',
		'Borki',
		'Borzechów',
		'Brze¼no',
		'Bychawa',
		'Che³m',
		'Chodel',
		'Chrzanów',
		'Cichobórz k. Hrubieszowa',
		'Ciecierzyn',
		'Cyców',
		'Czemierniki',
		'Czu³czyce',
		'Dêbina',
		'Dêblin',
		'Dêbowa K³oda',
		'Do³hobyczów',
		'Dorohusk',
		'Drelów',
		'Dubienka',
		'Dzierzkowice',
		'Dzwola',
		'Fajs³awice',
		'Firlej',
		'Frampol',
		'Garbów',
		'Godziszów',
		'Go³±b',
		'Goraj',
		'Gorzków',
		'Go¶cieradów',
		'Góra Pu³awska',
		'Grabowiec',
		'Hanna',
		'Hañsk',
		'Horod³o',
		'Horostyta',
		'Horyszów',
		'Hrebenne',
		'Hrubieszów',
		'Hulcze',
		'Huta D±browa',
		'Izbica',
		'Jab³eczna',
		'Jab³onna',
		'Jab³oñ',
		'Janowiec',
		'Janów Lubelski',
		'Janów Podlaski',
		'Jarczów',
		'Jastków',
		'Jeziorzany',
		'Józefów',
		'Kamieñ',
		'Kamionka',
		'Kanie',
		'Karczmiska',
		'Kazimierz Dolny',
		'K±kolewnica Wschodnia',
		'K³oczew',
		'Kock',
		'Kodeniec',
		'Kodeñ',
		'Komarów-Osada',
		'Komarówka Podlaska',
		'Konstantynów',
		'Koñskowola',
		'Krasnobród',
		'Krasnystaw',
		'Kra¶niczyn',
		'Kra¶nik',
		'Krynice',
		'Krzczonów',
		'Krzywda',
		'Ksiê¿pol',
		'Kurów',
		'Le¶na Podlaska',
		'Le¶niowice',
		'Lubartów',
		'Lubycza Królewska',
		'Ludwin',
		'£abunie',
		'£aszczów',
		'£aziska',
		'£êczna',
		'£omazy',
		'£opiennik Górny',
		'£owcza',
		'£ukowa',
		'£uków',
		'Majdan Sopocki',
		'Ma³aszewicze',
		'Markuszów',
		'Me³giew',
		'Mi±czyn',
		'Michalów',
		'Michów',
		'Miêdzyrzec Podlaski',
		'Milanów',
		'Milejów',
		'Mircze',
		'Modliborzyce',
		'Mojs³awice',
		'Motycz',
		'Na³êczów',
		'Niedrzwica Du¿a',
		'Niedrzwica Ko¶cielna',
		'Nied¼wiada',
		'Nieledew',
		'Nielisz',
		'Niemce',
		'Nowe Chojno',
		'Nowodwór',
		'Obsza',
		'Okrzeja',
		'Okszów',
		'Okuninka',
		'Olbiêcin',
		'Opole Lubelskie',
		'Or³ów Murowany',
		'Ostrów Lubelski',
		'Ostrówek',
		'Parczew',
		'Paw³ów',
		'Piaski',
		'Piszczac',
		'Podedwórze',
		'Poniatowa',
		'Popkowice',
		'Potok Górny',
		'Potok Wielki',
		'Pszczela Wola',
		'Puchaczów',
		'Pu³awy',
		'Rachanie',
		'Radecznica',
		'Radzyñ Podlaski',
		'Rejowiec',
		'Rejowiec Fabryczny',
		'Rokitno',
		'Rossosz',
		'Ró¿anka',
		'Ruda-Huta',
		'Rudnik',
		'Rybczewice',
		'Ryki',
		'Sawin',
		'Serniki',
		'Serokomla',
		'Siedliszcze',
		'Sielec',
		'Siemieñ',
		'Siennica Nadolna',
		'Siennica Ró¿ana',
		'Sitno',
		'Skierbieszów',
		'S³awatycze',
		'Sosnowica',
		'Sosnówka',
		'Spiczyn',
		'Stanin',
		'Stary Brus',
		'Stary Majdan',
		'Stary Zamo¶æ',
		'Staw',
		'Stê¿yca',
		'Stoczek £ukowski',
		'Stró¿a',
		'Strzy¿ewice',
		'Strzy¿ów',
		'Suchowola',
		'Su³ów',
		'Susiec',
		'Swory',
		'Szaniawy-Matysy',
		'Szastarka',
		'Szczebrzeszyn',
		'¦widnik',
		'Tarnawatka',
		'Tarnogród',
		'Telatyn',
		'Terespol',
		'Tereszpol',
		'T³u¶ciec',
		'Tomaszowice',
		'Tomaszów Lubelski',
		'Trawniki',
		'Trzebieszów',
		'Trzeszczany',
		'Trzydnik Du¿y',
		'Tuchowicz',
		'Tuczna',
		'Turkowice',
		'Turobin',
		'Tyszowce',
		'Uchanie',
		'Ulan-Majorat',
		'Ulhówek',
		'U³ê¿',
		'Urszulin',
		'Urzêdów',
		'U¶cimów',
		'W±wolnica',
		'Werbkowice',
		'Wierzbica',
		'Wilczopole',
		'Wilko³az',
		'Wilków',
		'Wisznice',
		'W³odawa',
		'Wohyñ',
		'Wojciechów',
		'Wojcieszków',
		'Wojs³awice',
		'Wola Gu³owska',
		'Wola Mys³owska',
		'Wola Uhruska',
		'Wrzelowiec',
		'Wyryki',
		'Wysokie',
		'Zakrzew',
		'Zakrzówek',
		'Zalesie',
		'Zamo¶æ',
		'Zawada',
		'Zawadówka',
		'Zdzi³owice',
		'Zembry',
		'Zwierzyniec',
		'¯mud¼',
		'¯ó³kiewka',
		'¯uków k. W³odawy',
		'¯yrzyn'
	);
	$lubuskie = array(
		'lubuskie',
		'Gorzów Wielkopolski',
		'Babimost',
		'Bledzew',
		'Bobrowice',
		'Bobrówko',
		'Bogdaniec',
		'Bojad³a',
		'Brody',
		'Brójce',
		'Brze¼nica',
		'Bytnica',
		'Bytom Odrzañski',
		'Cigacice',
		'Cybinka',
		'Czerwieñsk',
		'D±bie',
		'Deszczno',
		'Dobiegniew',
		'Drezdenko',
		'Goraj',
		'Gozdnica',
		'Górzyca',
		'Gubin',
		'I³owa',
		'Jasieñ',
		'Kargowa',
		'K³odawa Gorzowska',
		'Kolsko',
		'Kostrzyn',
		'Ko¿uchów',
		'Krosno Odrzañskie',
		'Krzeszyce',
		'Letnica',
		'Lipinki £u¿yckie',
		'Lubiszyn',
		'Lubniewice',
		'Lubrza',
		'Lubsko',
		'£agów',
		'£êknica',
		'Ma³omice',
		'Maszewo',
		'Miêdzyrzecz',
		'Niegos³awice',
		'Nietkowice',
		'Nowa Sól',
		'Nowe Czaple',
		'Nowe Miasteczko',
		'Nowogród Bobrzañski',
		'Ochla',
		'Olszyna',
		'O¶no Lubuskie',
		'Otyñ',
		'Przewóz',
		'Przylep',
		'Przytoczna',
		'Pszczew',
		'Racula',
		'Rzepin',
		'Santok',
		'Siedlisko',
		'Sk±pe',
		'Skwierzyna',
		'S³awa',
		'S³oñsk',
		'S³ubice',
		'Stare Kurowo',
		'Stary Kisielin',
		'Strzelce Krajeñskie',
		'Sulechów',
		'Sulêcin',
		'Szczaniec',
		'Szlichtyngowa',
		'Szprotawa',
		'¦widnica',
		'¦wiebodzin',
		'¦wiecko',
		'Templewo',
		'Torzym',
		'Trzciel',
		'Trzebiechów',
		'Trzebiel',
		'Tuplice',
		'Wêdrzyn',
		'Witnica',
		'Wschowa',
		'Wymiarki',
		'Zabór',
		'Zawada',
		'Zb±szynek',
		'Zielona Góra',
		'Zwierzyn',
		'¯agañ',
		'¯ary'
	);
	$malopolskie = array(
		'malopolskie',
		'Kraków',
		'Alwernia',
		'Andrychów',
		'Babice k. Alwerni',
		'Balice k. Krakowa',
		'Barcice',
		'Biadoliny Szlacheckie',
		'Bia³ka Tatrzañska',
		'Bia³y Dunajec',
		'Biecz',
		'Bielcza k. Brzeska',
		'Bieñkówka',
		'Bobowa k. Stró¿',
		'Bobrek k. O¶wiêcimia',
		'Bochnia',
		'Bogucice',
		'Bogumi³owice',
		'Bolechowice',
		'Boles³aw k. Olkusza',
		'Boles³aw k. Tarnowa',
		'Borki k. D±browy Tarnowskiej',
		'Borzêcin',
		'Bratucice',
		'Bru¶nik',
		'Brzesko',
		'Brzeszcze',
		'Brzezie k. Niepo³omic',
		'Brze¼nica k. Skawiny',
		'Brzozowa',
		'Budzów k. Suchej Beskidzkiej',
		'Bukowina Tatrzañska',
		'Bukowno k. Olkusza',
		'Bulowice k. O¶wiêcimia',
		'Bystra k. Jordanowa',
		'Chabówka',
		'Charsznica k. Miechowa',
		'Che³mek',
		'Che³miec',
		'Chocho³ów',
		'Chocznia',
		'Chrzanów',
		'Chy¿ne k. Nowego Targu',
		'Ciche k. Czarnego Dunajca',
		'Ciê¿kowice k. Tarnowa',
		'Czarny Dunajec',
		'Czchów',
		'Czermna k. Jas³a',
		'Czernichów',
		'Æwików',
		'D±browa Tarnowska',
		'Dêbno',
		'Dêbno k. Nowego Targu',
		'Dobczyce',
		'Dobra k. Limanowej',
		'Drwinia',
		'Dzianisz',
		'Dziewin',
		'Florynka',
		'Frydman na Spiszu',
		'Frydrychowice',
		'Gdów',
		'G³ogoczów',
		'Gnojnik',
		'Go³cza',
		'Go³kowice Dolne',
		'Gorenice',
		'Gorlice',
		'Grêboszów',
		'Grojec',
		'Gromnik',
		'Gródek n. Dunajcem',
		'Gruszów',
		'Grybów',
		'Hucisko',
		'Igo³omia',
		'Iwanowice k. S³omnik',
		'Iwkowa',
		'Izdebnik k. Kalwarii Zebrzydowskiej',
		'Jab³onka Orawska',
		'Jadowniki k. Brzeska',
		'Jadowniki Mokre',
		'Janowice k. Zakliczyna',
		'Jaroszowiec',
		'Jastrzêbia k. Tarnowa',
		'Jawiszowice',
		'Jazowsko',
		'Jerzmanowice',
		'Jod³ownik',
		'Jod³ówka Tuchowska',
		'Jordanów',
		'Jurgów',
		'Jurków k. Limanowej',
		'Juszczyn',
		'Kalwaria Zebrzydowska',
		'Kamienica k. £±cka',
		'Kamieñ',
		'Kamionka Wielka',
		'Kamionna k. Bochni',
		'Karniowice',
		'Kasina Wielka',
		'Kasinka Ma³a',
		'Kêty',
		'Klecza Górna',
		'Klêczany',
		'Klikuszowa',
		'Klimontów k. Miechowa',
		'Klucze',
		'Kluszkowce',
		'K³aj',
		'Kobylanka',
		'Kocmyrzów',
		'Koniusza',
		'Korzenna',
		'Koszyce',
		'Koszyce Wielkie',
		'Ko¶cielisko',
		'Kowalowa',
		'Koz³ów k. Miechowa',
		'Kro¶cienko n. Dunajcem',
		'Królówka',
		'Kru¿lowa Wy¿na',
		'Kryg',
		'Krynica',
		'Krzczonów k. My¶lenic',
		'Krzeszowice',
		'Krzeszów k. ¯ywca',
		'Krzyszkowice',
		'Krzywaczka',
		'Ksi±¿ Wielki k. Miechowa',
		'Lachowice k. ¯ywca',
		'Lanckorona',
		'Laskowa',
		'Leñcze',
		'Le¶nica k. Nowego Targu',
		'Libi±¿',
		'Libusza',
		'Limanowa',
		'Lipinki k. Biecza',
		'Lipnica Ma³a',
		'Lipnica Murowana',
		'Lipnica Wielka k. Grybowa',
		'Lipnica Wielka na Orawie',
		'Lisia Góra',
		'Liszki',
		'Lubcza k. Jas³a',
		'Lubieñ k. My¶lenic',
		'Lubomierz k. Limanowej',
		'Lud¼mierz',
		'Luszowice',
		'£abowa',
		'£apanów',
		'£apczyca',
		'£apsze Ni¿ne',
		'£±cko k. Nowego S±cza',
		'£êg Tarnowski',
		'£êtownia k. Jordanowa',
		'£omnica Zdrój',
		'£opuszna k. Nowego Targu',
		'£osie',
		'£ososina Dolna',
		'£ukowica k. Limanowej',
		'£u¿na',
		'£ysa Góra',
		'Maków Podhalañski',
		'Maniowy',
		'Marcinkowice k. Brzeska',
		'Marcinkowice k. Nowego S±cza',
		'Mêcina',
		'Mêdrzechów',
		'Micha³owice',
		'Miechów',
		'Minoga',
		'M³oszowa',
		'Modlnica',
		'Mogilany k. Krakowa',
		'Mogilno k. Nowego S±cza',
		'Morawica k. Krakowa',
		'Moszczenica k. Gorlic',
		'Mszana Dolna',
		'Mszana Górna',
		'Mucharz',
		'Murzasichle',
		'Muszyna',
		'My¶lachowice',
		'My¶lenice',
		'Nawojowa',
		'Nieczajna',
		'Niedomice',
		'Niedzica',
		'Nied¼wied¼ k. Limanowej',
		'Niegowiæ k. Bochni',
		'Niepo³omice',
		'Nowa Bia³a',
		'Nowa Jastrz±bka',
		'Nowa Wie¶ k. Kêt',
		'Nowe Brzesko',
		'Nowe Rybie',
		'Nowy S±cz',
		'Nowy Targ',
		'Nowy Wi¶nicz',
		'Ochotnica Dolna',
		'Ochotnica Górna',
		'Odrow±¿ Podhalañski',
		'Ojców',
		'Olesno k. D±browy Tarnowskiej',
		'Olkusz',
		'Olszówka k. Limanowej',
		'Olszyny',
		'Olszyny k. Jas³a',
		'O³piny',
		'Osiek k. O¶wiêcimia',
		'Osielec',
		'O¶wiêcim',
		'Otfinów',
		'Pale¶nica',
		'Pa³ecznica k. Miechowa',
		'Paszkówka',
		'Pcim',
		'Piekielnik',
		'Piwniczna-Zdrój',
		'Ple¶na',
		'P³aza',
		'Podegrodzie',
		'Pod³ê¿e k. Krakowa',
		'Podwilk na Orawie',
		'Pogórska Wola',
		'Polanka Wielka',
		'Por±bka Iwkowska',
		'Por±bka Uszewska',
		'Poronin',
		'Proszowice',
		'Przecieszyn',
		'Przeciszów',
		'Przeginia',
		'Przybys³awice',
		'Przyszowa',
		'Przytkowice',
		'Ptaszkowa',
		'Raba Wy¿na',
		'Rabka',
		'Raciechowice',
		'Rac³awice k. Miechowa',
		'Radgoszcz k. Tarnowa',
		'Rad³ów k. Tarnowa',
		'Radziemice',
		'Radziszów k. Skawiny',
		'Rajbrot',
		'Ropa',
		'Ro¿nowice',
		'Ro¿nów',
		'Rudawa k. Krakowa',
		'Rybna k. Krakowa',
		'Ryczów',
		'Ryglice',
		'Rytro',
		'Rzepiennik Strzy¿ewski',
		'Rzezawa',
		'Rzuchowa',
		'Sêkowa',
		'Sidzina k. Jordanowa',
		'Siedlce k. Nowego S±cza',
		'Siedliska k. Gorlic',
		'Siedliska k. Tuchowa',
		'Siemiechów k. Tuchowa',
		'Sieniawa k. Nowego Targu',
		'Siepraw',
		'Ska³a pod Ojcowem',
		'Skawa',
		'Skawica',
		'Skawina',
		'Skomielna Bia³a',
		'Skomielna Czarna',
		'Skrzydlna',
		'Skrzyszów',
		'S³aboszów',
		'S³omniki',
		'S³opnice Limanowskie',
		'Smardzowice k. Krakowa',
		'Smêgorzów',
		'Sobolów',
		'Spytkowice k. Chabówki',
		'Spytkowice k. Zatora',
		'Sromowce Wy¿ne',
		'Stadniki',
		'Stary S±cz',
		'Staszkówka',
		'Stronie k. Wadowic',
		'Stró¿a k. My¶lenic',
		'Stró¿e k. Gorlic',
		'Stryszawa',
		'Stryszów',
		'Strzelce Wielkie',
		'Sucha Beskidzka',
		'Su³kowice',
		'Su³kowice k. Andrychowa',
		'Su³oszowa',
		'Szaflary',
		'Szalowa',
		'Szczawa',
		'Szczawnica',
		'Szczepanów k. Brzeska',
		'Szczucin k. Tarnowa',
		'Szczurowa',
		'Szczyrzyc k. Limanowej',
		'Szerzyny',
		'Szymbark k. Gorlic',
		'Szynwa³d k. Tarnowa',
		'¦nietnica',
		'¦wi±tniki Górne',
		'Tarnawa k. Bochni',
		'Tarnowiec k. Tarnowa',
		'Tarnów',
		'Tenczynek',
		'Têgoborze',
		'Tokarnia',
		'Trzciana k. Bochni',
		'Trzebinia',
		'Trzebunia k. My¶lenic',
		'Trzeme¶nia',
		'Trzyci±¿',
		'Tuchów',
		'Turza k. Gorlic',
		'Tylicz',
		'Tylmanowa',
		'Tymbark',
		'Tymowa',
		'Ujanowice',
		'Uszew',
		'U¶cie Gorlickie',
		'U¶cie Solne',
		'Wadowice',
		'Waksmund',
		'Wa³ Ruda',
		'Wawrzeñczyce',
		'Wêgrzce k. Krakowa',
		'Wêgrzce Wielkie',
		'Wieliczka',
		'Wielka Wie¶ k. Krakowa',
		'Wielkie Drogi',
		'Wielog³owy',
		'Wieprz k. Andrychowa',
		'Wierzchos³awice Tarnowskie',
		'Wietrzychowice',
		'Wilkowisko',
		'Wi¶niowa k. Dobczyc',
		'Witanowice',
		'Witów k. Zakopanego',
		'W³osienica',
		'Wojnicz',
		'Wola Radziszowska',
		'Wola Rzêdziñska',
		'Wolbrom',
		'Wysoka k. Wadowic',
		'Wysowa',
		'Zabierzów Bocheñski',
		'Zabierzów k. Krakowa',
		'Zaborów k. Brzeska',
		'Zagórzany',
		'Zagórze k. Chrzanowa',
		'Zakliczyn k. My¶lenic',
		'Zakliczyn n. Dunajcem',
		'Zakopane',
		'Zalasowa',
		'Zalipie k. D±browy Tarnowskiej',
		'Zator',
		'Zawoja',
		'Z±b',
		'Zegartowice',
		'Zembrzyce',
		'Zg³obice',
		'Zielonki',
		'Z³ockie',
		'Z³ota',
		'Zubrzyca Górna',
		'¯abno k. Tarnowa',
		'¯egiestów'
	);
	$mazowieckie = array(
		'mazowieckie',
		'Warszawa',
		'Andrzejewo',
		'Baboszewo',
		'Baniocha',
		'Baranowo k. Ostro³êki',
		'Baranów',
		'Belsk',
		'Bia³a',
		'Bia³obrzegi',
		'Bielany',
		'Bielsk',
		'Bie¿uñ',
		'Blichowo',
		'B³êdów',
		'B³onie',
		'Bodzanów',
		'Boguty',
		'Bojmie',
		'Borkowice',
		'Borowie',
		'Bo¿ewo',
		'Brañszczyk',
		'Brochów',
		'Brok',
		'Brudzeñ',
		'Brwinów',
		'Bulkowo',
		'Ceg³ów',
		'Celestynów',
		'Ceranów',
		'Chlewiska',
		'Chorzele',
		'Chotcza-Józefów',
		'Chotomów',
		'Chynów',
		'Ciechanów',
		'Cieksyn',
		'Ciepielów',
		'Czarnia',
		'Czernice Borowe',
		'Czerwin',
		'Czerwiñsk n. Wis³±',
		'Czerwonka',
		'Czosnów',
		'Czury³y',
		'Dalekie',
		'D±browa',
		'D±brówka',
		'Dêbe Wielkie',
		'D³ugosiod³o',
		'Dobre',
		'Dobrzyków',
		'Domanice',
		'Dr±¿d¿ewo',
		'Drobin',
		'Drwalew',
		'Dziektarzewo',
		'Dzierz±¿nia',
		'Dzierzgowo',
		'Dzier¿enin',
		'Garbatka-Letnisko',
		'Garwolin',
		'G±bin',
		'G±sewo',
		'G±socin',
		'Gielniów',
		'Glinianka',
		'Glinojeck',
		'G³osków',
		'G³owaczów',
		'Gniewoszów',
		'Goleszyn',
		'Go³ymin-O¶rodek',
		'Gostynin',
		'Gostynin-Kruk',
		'Goszczyn',
		'Goworowo',
		'Gozdowo',
		'Gójsk',
		'Góra Kalwaria',
		'Górki',
		'Górzno',
		'Gózd',
		'Grabów n. Pilic±',
		'Grêbków',
		'Grodziec k. P³oñska',
		'Grodzisk Mazowiecki',
		'Grójec',
		'Grudusk',
		'Guzów',
		'Gzy',
		'Halinów',
		'Ho³owczyce',
		'Huszlew',
		'I³ów',
		'I³¿a',
		'Izabelin',
		'Jab³onna',
		'Jab³onna Lacka',
		'Jadów',
		'Jaktorów',
		'Jakubów',
		'Janki',
		'Jasienica',
		'Jasieniec',
		'Jastrz±b',
		'Jastrzêbia',
		'Jedliñsk',
		'Jedlnia-Letnisko',
		'Jednoro¿ec',
		'Jelonki',
		'Jeruzal',
		'Je¿ewo',
		'Joniec',
		'Józefów',
		'Kadzid³o',
		'Ka³uszyn',
		'Kamieñczyk',
		'Kampinos',
		'Karczew',
		'Karniewo',
		'Kazanów',
		'Klembów',
		'Klwów',
		'K³udzienko',
		'Koby³ka',
		'Ko³biel',
		'Komorów',
		'Konopki',
		'Konstancin-Jeziorna',
		'Korczew',
		'Korytnica',
		'Kosów Lacki',
		'Kotuñ',
		'Kowala Stêpocina',
		'Kozienice',
		'Krasiniec',
		'Krasne',
		'Krasnosielc',
		'Krzesk-Królowa Niwa',
		'Krze¶lin',
		'Krzynow³oga Ma³a',
		'Kuczbork-Osada',
		'Kuligów',
		'Latowicz',
		'Legionowo',
		'Lelice',
		'Lelis',
		'Leoncin',
		'Leszno k. B³onia',
		'Lesznowola',
		'Ligowo',
		'Lipa k. Przasnysza',
		'Lipiñskie',
		'Lipniki',
		'Lipowiec Ko¶cielny',
		'Lipsko',
		'Lubotyñ',
		'Lubowidz',
		'Lucieñ',
		'Lutocin',
		'£askarzew',
		'£±ck',
		'£êg-Probostwo',
		'£ochów',
		'£omianki',
		'£osice',
		'£yse',
		'Maciejowice',
		'Magnuszew',
		'Maków Mazowiecki',
		'Ma³a Wie¶',
		'Ma³kinia',
		'Marki',
		'Miastków Ko¶cielny',
		'Micha³owice',
		'Miedzna',
		'Miêdzyborów',
		'Milanówek',
		'Miñsk Mazowiecki',
		'Miszewo Murowane',
		'M³awa',
		'M³ochów',
		'M³odzieszyn',
		'M³ynarze',
		'Mochowo',
		'Mogielnica',
		'Mokobody',
		'Mordy',
		'Mrozy',
		'Mszczonów',
		'Myszyniec',
		'Nacpolsk',
		'Nadarzyn',
		'Naruszewo',
		'Nasielsk',
		'Niedzbórz',
		'Niemojki',
		'Nieporêt',
		'Nowa Sucha',
		'Nowa Wie¶',
		'Nowe Miasto',
		'Nowe Miasto n. Pilic±',
		'Nowe Proboszczewice',
		'Nowy Duninów',
		'Nowy Dwór Mazowiecki',
		'Nowy Kazuñ',
		'Nowy Lubiel',
		'Nowy Szelków',
		'Nur',
		'Obryte',
		'Odrzywó³',
		'Ojrzeñ',
		'Okuniew',
		'Olszanka',
		'Olszewo-Borki',
		'Opinogóra-Górna',
		'Oroñsko',
		'Osieck',
		'Ostro³êka',
		'Ostrów Mazowiecka',
		'Ostrówek',
		'Osuchów',
		'O¶cis³owo',
		'Otrêbusy',
		'Otwock',
		'O¿arów Mazowiecki',
		'Pacyna',
		'Paprotnia',
		'Parysów',
		'Paw³owice',
		'Piaseczno k. Warszawy',
		'Piastów',
		'Pilawa',
		'Pionki',
		'Piski',
		'Platerów',
		'P³ochocin',
		'P³ock',
		'P³oniawy-Bramura',
		'P³oñsk',
		'Pniewo',
		'Pniewy',
		'Podkowa Le¶na',
		'Pokrzywnica',
		'Policzna',
		'Pomiechówek',
		'Popowo Ko¶cielne',
		'Porêba-Kocêby',
		'Po¶wiêtne',
		'Potworów',
		'Promna',
		'Prostyñ',
		'Pruszków',
		'Przasnysz',
		'Przesmyki',
		'Przy³êk',
		'Przysucha',
		'Przytyk',
		'Pu³tusk',
		'Pustelnik Miñski',
		'Puszcza Mariañska',
		'Raci±¿',
		'Radom',
		'Radzanowo',
		'Radzanów',
		'Radziejowice',
		'Radziwi³³ów',
		'Radzymin',
		'Raszyn',
		'Regimin',
		'Repki',
		'Rogozino',
		'Ro¶ciszewo',
		'Rozniszew',
		'Ró¿an',
		'Rusinów',
		'Rybno',
		'Ryczywó³',
		'Rz±¶nik',
		'Rzeczniów',
		'Rzekuñ',
		'Rzewnie',
		'Sabnie',
		'Sadowne',
		'Sanniki',
		'Sarnaki',
		'Serock',
		'Seroczyn',
		'Sieciechów',
		'Siecieñ',
		'Siedlce',
		'Siemi±tkowo-Koziebrodzkie',
		'Siennica',
		'Sienno',
		'Sierpc',
		'Sikórz',
		'Skaryszew',
		'Skórzec',
		'Skrzeszew',
		'Skrzeszewy',
		'S³omczyn',
		'S³ubice',
		'S³upia',
		'S³upno',
		'Sobienie-Jeziory',
		'Sobików',
		'Sobolew',
		'Sochaczew',
		'Sochocin',
		'Soczewka',
		'Soko³ów Podlaski',
		'Solec n. Wis³±',
		'Somianka',
		'Soñsk',
		'Stanis³awów',
		'Stara B³otnica',
		'Stara Kornica',
		'Stare Babice',
		'Stare Gralewo',
		'Stare Za³ubice',
		'Staro¼reby',
		'Stary Brzozów',
		'Stary Mirów',
		'Sterdyñ',
		'Stoczek',
		'Strachówka',
		'Stromiec',
		'Strzegowo',
		'Stupsk',
		'Sucho¿ebry',
		'Sulejówek',
		'Syberia',
		'Sypniewo',
		'Szczawin',
		'Szczutowo',
		'Szczytno',
		'Szreñsk',
		'Szulborze Wielkie',
		'Szyd³owiec k. Radomia',
		'Szyd³owo',
		'Szymanów',
		'¦wiercze',
		'Tarczyn',
		'Tczów',
		'Teresin',
		'T³uszcz',
		'Trojanów',
		'Troszyn',
		'Tu³owice k. Sochaczewa',
		'Urle',
		'Warka',
		'W±sewo',
		'Weso³a',
		'Wêgrów',
		'Wi±zowna',
		'Wieczfnia Ko¶cielna',
		'Wieliszew',
		'Wieniawa',
		'Wierzbica',
		'Wierzbno',
		'Wilga',
		'Winnica',
		'Wiskitki',
		'Wi¶niew',
		'Wi¶niewo',
		'Wodynie',
		'Wola Mystkowska',
		'Wola Pra¿mowska',
		'Wola Rasztowska',
		'Wola Rêbkowska',
		'Wolanów',
		'Wo³omin',
		'Wólka Kosowska',
		'Wyszków',
		'Wyszogród',
		'Wyszyny Ko¶cielne',
		'Wy¶mierzyce',
		'Zaborów',
		'Zabrodzie',
		'Zakroczym',
		'Zakrzew',
		'Zalas',
		'Zalasowa',
		'Za³uski',
		'Zarêby',
		'Zarêby Ko¶cielne',
		'Zatory',
		'Zawidz Ko¶cielny',
		'Z±bki',
		'Zbuczyn',
		'Zegrze',
		'Zegrze Po³udniowe',
		'Zembrów',
		'Zielona',
		'Zielonka',
		'Z³otok³os',
		'Zuzela',
		'Zwoleñ',
		'¯abia Wola',
		'¯elechów',
		'¯eliszew',
		'¯uromin',
		'¯yrardów'
	);
	$opolskie = array(
		'opolskie',
		'Opole',
		'Baborów',
		'B±ków',
		'Bia³a',
		'Bia³a Nyska',
		'Bierawa',
		'B³otnica Strzelecka',
		'Bodzanowice',
		'Bogacica',
		'Branice',
		'Brzeg',
		'Brzezie',
		'Bukowa ¦l±ska',
		'Bukowie',
		'Burgrabice',
		'Byczyna',
		'Chró¶cice',
		'Chró¶cina',
		'Chrz±stowice',
		'Chudoba',
		'Cisek',
		'Czarnow±sy',
		'Czeska Wie¶',
		'Dalachów',
		'D±browa',
		'Dobrodzieñ',
		'Dobrzeñ Wielki',
		'Domaszowice',
		'Dylaki',
		'Dziergowice',
		'G³ogówek',
		'G³ubczyce',
		'G³ucho³azy',
		'G³uszyna',
		'Gogolin',
		'Gorzów ¦l±ski',
		'Gostomia',
		'Go¶ciêcin',
		'Go¶winowice',
		'Góra ¦wiêtej Anny',
		'Góra¿d¿e',
		'Gracze',
		'Grodków',
		'Idzikowice',
		'Izbicko',
		'Jarno³tów',
		'Jarno³tówek',
		'Jasienica Dolna',
		'Jemielnica',
		'Jêdrzejów',
		'Kad³ub',
		'Ka³ków',
		'Kamiennik',
		'Kamieñ ¦l±ski',
		'Kar³owice',
		'Kar³owice Wielkie',
		'Kêdzierzyn-Ko¼le',
		'Kielcza',
		'Kietrz',
		'Kluczbork',
		'Kolonowskie',
		'Komprachcice',
		'Korfantów',
		'Ko¶cieliska',
		'Kotlarnia',
		'Kórnica',
		'Krapkowice',
		'Krzywiczyny',
		'Kujakowice Górne',
		'Kup',
		'Lasowice Ma³e',
		'Lasowice Wielkie',
		'Le¶nica',
		'Lewin Brzeski',
		'Ligota Ksi±¿êca',
		'Ligota Turawska',
		'Lisiêcice',
		'Luboszyce',
		'Lubrza',
		'Lubsza',
		'£ambinowice',
		'£±cznik',
		'£osiów',
		'£ubniany',
		'M±koszyce',
		'Mokre',
		'Murów',
		'Namys³ów',
		'Niemodlin',
		'Niwnica',
		'Nowa Cerekwia',
		'Nowy ¦wiêtów',
		'Nysa',
		'Olesno',
		'Olszanka',
		'Osowiec ¦l±ski',
		'Otmuchów',
		'Ozimek',
		'Paczków',
		'Pakos³awice',
		'Paw³owiczki',
		'Pisarzowice',
		'Pludry',
		'Poborszów',
		'Pokój',
		'Polska Cerekiew',
		'Popielów',
		'Praszka',
		'Prószków',
		'Prudnik',
		'Przechód',
		'Przylesie',
		'Radawie',
		'Rad³ów',
		'Reñska Wie¶',
		'Rozmierz',
		'Rudniki',
		'Scinawa Ma³a',
		'Siemys³ów',
		'Ska³±gi',
		'Skarbimierz',
		'Skorogoszcz',
		'Skoroszyce',
		'Smardy Dolne',
		'Stare Budkowice',
		'Stare Sio³kowice',
		'Sternalice',
		'Strzegów',
		'Strzelce Opolskie',
		'Strzeleczki',
		'Szczedrzyk',
		'Szyd³owice',
		'Szymiszów',
		'Szymonków',
		'¦wierczów',
		'Tarnów Opolski',
		'Tu³owice',
		'Turawa',
		'Twardawa',
		'Ujazd',
		'Walce',
		'Wierzbica Górna',
		'Wierzbnik',
		'Wilków',
		'Wo³czyn',
		'Zakrzów',
		'Zawadzkie',
		'Zdzieszowice',
		'Zêbowice',
		'Zielina',
		'Zubrzyce',
		'¬linice'
	);
	$podkarpackie = array(
		'podkarpackie',
		'Rzeszów',
		'Adamówka',
		'Albigowa',
		'Babice n. Sanem',
		'Bachórz',
		'Bachórzec',
		'Baligród',
		'Baranów Sandomierski',
		'Basznia Dolna',
		'Besko',
		'Bêdziemy¶l',
		'Bia³obrzegi k. £añcuta',
		'Bie¼dziedza',
		'Bircza',
		'Blizne',
		'B³a¿owa Rzeszowska',
		'B³êdowa Tyczyñska',
		'Boguchwa³a',
		'Bojanów',
		'Borowa k. Mielca',
		'Bratkowice',
		'Bratkówka',
		'Brzeziny k. Ropczyc',
		'Brze¼nica Dêbicka',
		'Brzostek',
		'Brzozów',
		'Brzóza Królewska',
		'Brzyska',
		'Brzyska Wola',
		'Budziwój',
		'Bukowsko',
		'Ch³opice',
		'Chmielnik Rzeszowski',
		'Chmielów',
		'Chorkówka',
		'Chorzelów',
		'Cieklin',
		'Cieszanów',
		'Cisna',
		'Cmolas',
		'Czarna k. £añcuta',
		'Czarna k. Pilzna',
		'Czarna k. Ropczyc',
		'Czarna k. Ustrzyk Dolnych',
		'Czermin k. Mielca',
		'Czudec',
		'Dêbica',
		'Dêbno k. Le¿ajska',
		'Dêbowiec',
		'Dobrzechów',
		'Domaradz',
		'Domostawa',
		'Dubiecko',
		'Dukla',
		'Dwernik',
		'Dydnia',
		'Dyl±gowa',
		'Dyl±gówka',
		'Dynów',
		'Dzikowiec',
		'Fredropol',
		'Frysztak Kro¶nieñski',
		'Futoma',
		'Gaæ',
		'Gaw³uszowice',
		'G³ogów Ma³opolski',
		'G³owienka',
		'Gniewczyna £añcucka',
		'Gnojnica',
		'Gogo³ów',
		'Golcowa',
		'Gorzyce',
		'Górki Mieleckie',
		'Górno k. Rzeszowa',
		'Grabiny',
		'Grabownica Starzeñska',
		'Grêbów',
		'Grodzisko Dolne',
		'Grodzisko k. Strzy¿owa',
		'Grudna Dolna',
		'Gumniska',
		'Gwo¼nica Górna',
		'Haczów n. Wis³okiem',
		'Handzlówka',
		'Harasiuki',
		'Harklowa k. Jas³a',
		'Harta',
		'Hoczew k. Leska',
		'Horyniec',
		'Humniska',
		'Husów',
		'Huta Krzeszowska',
		'Hy¿ne k. Dynowa',
		'Iwierzyce',
		'Iwonicz-Zdrój',
		'Izdebki',
		'Jaæmierz',
		'Jarocin',
		'Jaros³aw',
		'Jasienica Rosielna',
		'Jasionka k. Rzeszowa',
		'Jasionów k. Brzozowa',
		'Jas³o',
		'Jaszczew',
		'Ja¶liska',
		'Jawornik Polski',
		'Jedlicze',
		'Je¿owe',
		'Jod³owa',
		'Jurowce',
		'Kalników',
		'Kamieñ k. Rudnika n. Sanem',
		'Kamionka k. Dêbicy',
		'Kañczuga',
		'Kaszyce k. Jaros³awia',
		'K±kolówka',
		'Klimkówka',
		'Kobylany',
		'Kolbuszowa',
		'Ko³aczyce',
		'Komañcza',
		'Kombornia',
		'Kopytowa',
		'Korczyna',
		'Kosina',
		'Kraczkowa',
		'Krasiczyn',
		'Krasne k. Rzeszowa',
		'Krempna',
		'Krosno',
		'Kro¶cienko Wy¿ne',
		'Krowica Sama',
		'Krzemienica',
		'Krzeszów',
		'Krzywcza n. Sanem',
		'Kury³ówka',
		'Ku¼mina',
		'Laszki k. Bobrówki',
		'Lesko',
		'Le¿ajsk',
		'Lipnica',
		'Lubaczów',
		'Lubatowa',
		'Lubenia',
		'Lubzina',
		'Lutcza k. Rzeszowa',
		'Lutowiska',
		'£añcut',
		'£±czki Jagielloñskie',
		'£±czki Kucharskie',
		'£±ka k. Rzeszowa',
		'£êki Dukielskie',
		'£êki Górne',
		'£êki Strzy¿owskie',
		'£êtownia k. Niska',
		'£opuszka Wielka',
		'£owce',
		'£ukawiec',
		'Maækowice',
		'Majdan Królewski',
		'Manasterz',
		'Markowa',
		'Markuszowa',
		'Medyka',
		'Medynia G³ogowska',
		'Miejsce Piastowe',
		'Mielec',
		'M³yny',
		'Mrowla',
		'Mrzyg³ód',
		'Munina',
		'Nagoszyn',
		'Narol',
		'Niebieszczany',
		'Niebylec',
		'Niechobrz',
		'Nied¼wiada k. Ropczyc',
		'Nienadówka',
		'Nisko',
		'Niwiska Kolbuszowskie',
		'Nowa Dêba',
		'Nowa Grobla',
		'Nowa Sarzyna',
		'Nowosielce Gniewosz',
		'Nowosió³ki Dydyñskie',
		'Nowotaniec',
		'Nowy ¯migród',
		'Nozdrzec',
		'Ocieka',
		'Odrzykoñ',
		'Oleszyce',
		'Olszanica',
		'Or³y',
		'Orzechowce',
		'Osiek Jasielski',
		'Osobnica',
		'Ostrów',
		'Padew Narodowa',
		'Pantalowice',
		'Pikulice',
		'Pilzno',
		'P³azów',
		'Polana',
		'Polañczyk',
		'Po³omia k. Rzeszowa',
		'Pruchnik',
		'Przec³aw',
		'Przemy¶l',
		'Przeworsk',
		'Przewrotne',
		'Przy³êk k. Mielca',
		'Przysieki',
		'Pstr±gowa',
		'Pustków',
		'Pysznica',
		'Radawa',
		'Radomy¶l n. Sanem',
		'Radomy¶l Wielki',
		'Radymno',
		'Rakszawa',
		'Rani¿ów',
		'Rokietnica k. Przemy¶la',
		'Ropczyce',
		'Ropienka',
		'Ro¼wienica',
		'Równe k. Dukli',
		'Ruda k. Mielca',
		'Ruda Ró¿aniecka',
		'Rudnik n. Sanem',
		'Rybotycze',
		'Rymanów',
		'Rymanów Zdrój',
		'Rzemieñ',
		'Rzeped¼',
		'Sanok',
		'Sarnów k. Mielca',
		'Sêdziszów Ma³opolski',
		'Siedliska n. Sanem',
		'Siedliska-Bogusz',
		'Sieniawa',
		'Sietesz',
		'Sko³yszyn',
		'Skopanie',
		'Soko³ów Ma³opolski',
		'Solina',
		'So¶nica k. Jaros³awia',
		'Stalowa Wola',
		'Stara Jastrz±bka',
		'Stary Dzików',
		'Stary Lubliniec',
		'Stêpina',
		'Straszêcin',
		'Straszydle',
		'Stra¿ów',
		'Strzegocice',
		'Strzy¿ów n. Wis³okiem',
		'Stubno',
		'Szebnie',
		'¦wiêcany k. Biecza',
		'¦wilcza',
		'Targowiska',
		'Tarnawa Dolna',
		'Tarnobrzeg',
		'Tarnowiec',
		'Tryñcza',
		'Trzciana k. Rzeszowa',
		'Trzebownisko',
		'Trze¶niów',
		'Trze¶ñ',
		'Trzêsówka',
		'Tuszów Narodowy',
		'Tuszyma',
		'Tyczyn',
		'Tylawa',
		'Tyrawa Wo³oska',
		'Uherce Mineralne',
		'Ulanów',
		'Ustrzyki Dolne',
		'Ustrzyki Górne',
		'Wadowice Górne',
		'Werchrata',
		'Weso³a k. Dynowa',
		'Wetlina',
		'Wêglówka',
		'Wi±zownica',
		'Wide³ka',
		'Wielkie Oczy',
		'Wielopole Skrzyñskie',
		'Wilcza Wola',
		'Wi¶niowa n. Wis³okiem',
		'Witry³ów',
		'Wojaszówka',
		'Wojtkowa',
		'Wola Rani¿owska',
		'Wola Zarczycka',
		'Wo³kowyja',
		'Wólka Pe³kiñska',
		'Wróblik Szlachecki',
		'Wysoka k. Rzeszowa',
		'Wysoka Strzy¿owska',
		'Wyszatyce',
		'Zaczernie',
		'Zagorzyce',
		'Zagórz',
		'Zaklików',
		'Zaleszany',
		'Zapa³ów',
		'Zarszyn',
		'Zarzecze k. Jaros³awia',
		'Zarzecze k. Rzeszowa',
		'Zasów',
		'Zbydniów',
		'Zdziarzec',
		'Zg³obieñ',
		'Zrêcin',
		'¯arówka',
		'¯ohatyn',
		'¯o³ynia',
		'¯urawica',
		'¯yraków'
	);
	$podlaskie = array(
		'podlaskie',
		'Bia³ystok',
		'Augustów',
		'Baka³arzewo',
		'Barg³ów Ko¶cielny',
		'Be³da',
		'Bia³aszewo',
		'Bia³owie¿a',
		'Bielsko-Bia³a',
		'Boæki',
		'Borkowo',
		'Brañsk',
		'Choroszcz',
		'Ciechanowiec',
		'Czarna Bia³ostocka',
		'Czartajew',
		'Czeremcha',
		'Czy¿e',
		'Czy¿ew-Osada',
		'D±browa Bia³ostocka',
		'Dobrzyniewo Ko¶cielne',
		'Drohiczyn',
		'Dubicze Cerkiewne',
		'Dziadkowice',
		'Filipów I',
		'Giby',
		'Goni±dz',
		'Grabowo',
		'Grajewo',
		'Gr±dy-Woniecko',
		'Gregorowce',
		'Grodzisk',
		'Gródek',
		'Hajnówka',
		'Jab³onka Ko¶cielna',
		'Janów',
		'Jasionówka',
		'Ja¶wi³y',
		'Jedwabne',
		'Jeleniewo',
		'Juchnowiec Ko¶cielny',
		'Juszkowy Gród',
		'Kleosin',
		'Kleszczele',
		'Klukowo',
		'Knyszyn',
		'Kobylin-Borzymy',
		'Kolno',
		'Ko³aki',
		'Korycin',
		'Krasnopol',
		'Krasnybór',
		'Krynki',
		'Krypno Ko¶cielne',
		'Kulesze Ko¶cielne',
		'Ku¼nica k. Sokó³ki',
		'Lachowo',
		'Laskowiec',
		'Lipsk',
		'£apy',
		'£om¿a',
		'Ma³y P³ock',
		'Miastkowo',
		'Micha³owo',
		'Mielnik',
		'Mikaszówka',
		'Milejczyce',
		'Mi³kowice-Maæki',
		'Monkinie',
		'Moñki',
		'Narew',
		'Narewka',
		'Nowe Piekuty',
		'Nowinka',
		'Nowogród',
		'Nowy Dwór',
		'Nurzec',
		'Orla',
		'Ostro¿any',
		'Perlejewo',
		'Pi±tnica Poduchowna',
		'P³aska',
		'Po¶wiêtne',
		'Przero¶l',
		'Przytu³y',
		'Puñsk',
		'Raczki',
		'Radzi³ów',
		'Rajgród',
		'Rudka',
		'Rutka-Tartak',
		'Rutki-Kossaki',
		'Ryga³ówka',
		'Sejny',
		'Sidra',
		'Siemiatycze',
		'Soko³y',
		'Sokó³ka',
		'Stary Folwark',
		'Stawiski',
		'Suchowola',
		'Supra¶l',
		'Sura¿',
		'Suwa³ki',
		'Szczuczyn',
		'Szepietowo',
		'Sztabin',
		'Szudzia³owo',
		'Szumowo',
		'Szymki',
		'Szypliszki',
		'¦ledzianów',
		'¦niadowo',
		'Trzcianne',
		'Turo¶l',
		'Turo¶ñ Ko¶cielna',
		'Tykocin',
		'Wasilków',
		'W±sosz',
		'Wizna',
		'Wi¿ajny',
		'Wygoda',
		'Wysokie Mazowieckie',
		'Wyszki',
		'Zab³udów',
		'Zambrów',
		'Zawady'
	);
	$pomorskie = array(
		'pomorskie',
		'Gdañsk',
		'Banie Mazurskie',
		'Barcino',
		'Barkowo',
		'Bar³o¿no',
		'Biñcze',
		'Bobowo k. Starogardu',
		'Bolszewo',
		'Borowy M³yn',
		'Borsk',
		'Borzechowo',
		'Borzestowo',
		'Borzêcino',
		'Borzytuchom',
		'Bo¿epole Wielkie',
		'Brodnica Górna',
		'Bruskowo Wielkie',
		'Brusy',
		'Brzezie',
		'Brze¼no Lêborskie',
		'Brze¼no Szlacheckie',
		'Budowo',
		'Bytów',
		'Cedry Wielkie',
		'Cewice',
		'Charzykowy',
		'Chmielno',
		'Choczewo',
		'Chojnice',
		'Chwaszczyno',
		'Czarna D±brówka',
		'Czarna Woda',
		'Czarne',
		'Czersk',
		'Cz³uchów',
		'Cz³uchów',
		'Damnica',
		'Debrzno',
		'Dêbnica Kaszubska',
		'Dretyñ',
		'Drewnica',
		'Dziemiany',
		'Dzierzgoñ',
		'Dzier¿±¿no',
		'E³ganowo',
		'Gardeja',
		'Gardna Wielka',
		'G±siorki',
		'Gdynia',
		'G³odowo',
		'G³ówczyce',
		'Gniew',
		'Gniewino',
		'Godziszewo',
		'Go³ubie',
		'Gorêczyno',
		'Gostkowo',
		'Go¶cicino',
		'Gotelp',
		'Gowidlino',
		'Grabowo Ko¶cierskie',
		'Hel',
		'Hopowo',
		'Jab³owo',
		'Jantar',
		'Jasieñ',
		'Jastarnia',
		'Jastrzêbia Góra',
		'Jezierzyce',
		'Jurata',
		'Kaliska',
		'Kamienica Królewska',
		'Kamienica Szlachecka',
		'Karsin',
		'Kartuzy',
		'Karwia',
		'Kasparus',
		'K±ty Rybackie',
		'Kêpice',
		'Kielno',
		'Kie³pino k. Kartuz',
		'Kleszczewo',
		'K³odawa Gdañska',
		'Kobylnica',
		'Kocza³a',
		'Kokoszkowy',
		'Kolbudy',
		'Koleczkowo',
		'Ko³czyg³owy',
		'Konarzyny k. Chojnic',
		'Konarzyny k. Zblewa',
		'Korne',
		'Korzybie',
		'Kosakowo',
		'Ko¶cierzyna',
		'Krokowa',
		'Krynica Morska',
		'Kusowo',
		'Ku¼nica',
		'Kwakowo',
		'Kwidzyn',
		'Le¶niewo',
		'Le¶no',
		'Lêbork',
		'Lichnowy k. Gdañska',
		'Linia',
		'Liniewo',
		'Lipnica',
		'Lipusz',
		'Lubichowo',
		'Lubiszewo k. Tczewa',
		'Luzino',
		'£±g',
		'£eba',
		'£ebcz',
		'£ebieñ',
		'£ebno',
		'£êczyce',
		'£êgowo',
		'£ubiana',
		'£upawa',
		'Malbork',
		'Ma³a Karczma',
		'Maszewo',
		'Miastko',
		'Miechucino',
		'Mierzeszyn',
		'Miko³ajki Pomorskie',
		'Mikorowo',
		'Mi³ob±dz',
		'Mi³oradz',
		'Mirachowo',
		'Morzeszczyn',
		'Mosty',
		'Motarzyno',
		'M¶ciszewice',
		'My¶lice',
		'Nakla',
		'Niezabyszewo',
		'Nowa Cerkiew k. Chojnic',
		'Nowa Cerkiew k. Morzeszczyna',
		'Nowa Karczma',
		'Nowa Wie¶ Lêborska',
		'Nowy Barkoczyn',
		'Nowy Dwór Gdañski',
		'Nowy Dwór Wejherowski',
		'Nowy Staw',
		'No¿yno',
		'Objazda',
		'Ocypel',
		'Ogorzeliny',
		'Opalenie',
		'Osieczna k. Czerska',
		'Osiek k. Skórcza',
		'Ostaszewo Gdañskie',
		'Parchowo',
		'P±czewo',
		'Pelplin',
		'Piaseczno k. Gniewa',
		'Piaszczyna',
		'Piece',
		'Pinczyn',
		'Pob³ocie',
		'Pogódki',
		'Polnica',
		'Po³chowo',
		'Pomieczyno',
		'Pomysk Wielki',
		'Potêgowo',
		'Prabuty',
		'Pruszcz Gdañski',
		'Przechlewo',
		'Przodkowo',
		'Przyja¼ñ',
		'Przytocko',
		'Przywidz',
		'Pszczó³ki',
		'Puck',
		'Reda',
		'Rekowo',
		'Rokity',
		'Rowy',
		'Roz³azino',
		'Rudno k. Pelplina',
		'Rumia',
		'Ryjewo',
		'Rytel',
		'Rzeczenica',
		'Sadlinki',
		'Sasino',
		'Sianowo k. Kartuz',
		'Siemirowice',
		'Sierakowice',
		'Skarszewy',
		'Skórcz',
		'S³upsk',
		'Smêtowo Graniczne',
		'Smo³dzino',
		'Sobowidz',
		'Somonino',
		'Sopieszyno',
		'Sopot',
		'Stara D±browa',
		'Stara Kiszewa',
		'Stare Gronowo',
		'Stare Polaszki',
		'Stare Pole',
		'Starogard Gdañski',
		'Stary Bukowiec',
		'Stary Dzierzgoñ',
		'Stary Targ',
		'Starzyno',
		'Stegna',
		'Stê¿yca Szlachecka',
		'Straszyn',
		'Strzebielino Morskie',
		'Strzepcz',
		'Studzienice',
		'Subkowy',
		'Suchorze',
		'Suchy D±b',
		'Sulêczyno',
		'Swaro¿yn',
		'Swornegacie',
		'Sycewice',
		'Szemud',
		'Szlachta',
		'Szropy',
		'Sztum',
		'Sztutowo',
		'Szymbark k. Kartuz',
		'Tczew',
		'Tr±bki Wielkie',
		'Trzebiatkowa',
		'Trzebielino',
		'Tuchomie',
		'Turze k. Tczewa',
		'Ustka',
		'Walichnowy',
		'W±glikowice',
		'Wdzydze',
		'Wejherowo',
		'Wicko',
		'Wiele',
		'Wielki Klincz',
		'Wierzchowo',
		'Wierzchucino k. Lêborka',
		'Wi¶lina',
		'Wi¶linka',
		'W³adys³awowo',
		'Wyczechy',
		'Wysin',
		'Zamostne',
		'Zblewo',
		'Zwartówko k. Lêborka',
		'¯elistrzewo',
		'¯elkowo',
		'¯ukowo k. Kartuz'
	);
	$slaskie = array(
		'slaskie',
		'Katowice',
		'Bestwina',
		'Bêdzin',
		'Bielsko-Bia³a',
		'Bieruñ',
		'Blachownia',
		'Bobrowniki',
		'Bojszowy',
		'Boronów',
		'Brenna',
		'Buczkowice',
		'Bystra',
		'Bystra ¦l±ska',
		'Bytom',
		'Cha³upki',
		'Che³m ¦l±ski',
		'Chorzów',
		'Chybie',
		'Ciasna',
		'Cieszyn',
		'Cykarzew',
		'Czaniec',
		'Czechowice-Dziedzice',
		'Czekanów',
		'Czelad¼',
		'Czernica',
		'Czernichów',
		'Czerwionka-Leszczyny',
		'Czêstochowa',
		'Czy¿owice',
		'Æwiklice',
		'Dankowice',
		'D±browa Górnicza',
		'D±browa Zielona',
		'Dêbowiec',
		'Dobieszowice',
		'Drogomy¶l',
		'Dziêgielów',
		'Gaszowice',
		'Giera³towice',
		'Gilowice',
		'Gliwice',
		'Gocza³kowice-Zdrój',
		'Godów',
		'Godziszka',
		'Golasowice',
		'Goleszów',
		'Go³kowice',
		'Gorzyce',
		'Gostyñ',
		'Górki Wielkie',
		'Ha¼lach',
		'Herby',
		'Imielin',
		'Irz±dze',
		'Istebna',
		'Jankowice',
		'Jankowice Rybnickie',
		'Janów',
		'Jasienica',
		'Jastrzêbie-Zdrój',
		'Jaworze',
		'Jaworzno',
		'Jaworzynka',
		'Jejkowice',
		'Jele¶nia',
		'Julianka',
		'Kaczyce',
		'Kalety',
		'Kamesznica',
		'Kamienica Polska',
		'Kamyk',
		'K³obuck',
		'K³omnice',
		'Knurów',
		'Kobiernice',
		'Kobiór',
		'Kochanowice',
		'Koniaków',
		'Koniecpol',
		'Konopiska',
		'Kornowac',
		'Koszarawa',
		'Koszêcin',
		'Kozieg³owy',
		'Kozy',
		'Kroczyce',
		'Krupski M³yn',
		'Kruszyna',
		'Krzanowice',
		'Krzepice',
		'Krzy¿anowice',
		'Krzy¿owa',
		'Ku¼nia Raciborska',
		'Lelów',
		'Lêdziny',
		'Ligota',
		'Lipie',
		'Lipowa',
		'Lisów',
		'Lubliniec',
		'Lubomia',
		'Lubsza',
		'Lyski',
		'£aziska Górne',
		'£azy',
		'£±ka',
		'£êkawica',
		'£odygowice',
		'£ugi-Rad³y',
		'Marklowice',
		'Mazañcowice',
		'Miasteczko ¦l±skie',
		'Mied¼na',
		'Mied¼no',
		'Mierzêcice',
		'Miêdzybrodzie Bialskie',
		'Miêdzyrzecze',
		'Miko³ów',
		'Milówka',
		'Mizerów',
		'Mstów',
		'Mszana',
		'Mykanów',
		'Mys³owice',
		'Myszków',
		'Nak³o',
		'Nêdza',
		'Niegowa',
		'Niegowonice',
		'Ogrodzieniec',
		'Olsztyn',
		'Opatów',
		'Ornontowice',
		'Orzesze',
		'Ostrowy n. Oksz±',
		'O¿arowice',
		'Palowice',
		'Paniówki',
		'Panki',
		'Parzymiechy',
		'Paw³owice',
		'Pawonków',
		'Piasek',
		'Piekary ¦l±skie',
		'Pietrowice Wielkie',
		'Pietrzykowice',
		'Pilchowice',
		'Pilica',
		'Pisarzowice',
		'P³awniowice',
		'Poczesna',
		'Pogwizdów',
		'Po³omia',
		'Poniszowice',
		'Popów',
		'Poraj',
		'Por±bka',
		'Porêba',
		'Prad³a',
		'Pruchna',
		'Przyrów',
		'Przystajñ',
		'Przyszowice',
		'Psary k. Bêdzin',
		'Pstr±¿na',
		'Pszczyna',
		'Pszów',
		'Pyskowice',
		'Racibórz',
		'Radlin',
		'Radziechowy',
		'Radzionków',
		'Rajcza',
		'Raszczyce',
		'Rêdziny',
		'Rogów',
		'Ruda ¦l±ska',
		'Rudnik',
		'Rudniki',
		'Rudy',
		'Rudzica',
		'Rudziniec',
		'Rybarzowice',
		'Rybnik',
		'Rydu³towy',
		'S±czów',
		'Siemianowice ¦l±skie',
		'Sierakowice',
		'Sieraków ¦l±ski',
		'Siewierz',
		'Skoczów',
		'Skrzyszów',
		'S³awków',
		'Sosnowiec',
		'So¶nicowice',
		'Stanis³awów',
		'Starcza',
		'Starokrzepice',
		'Strumieñ',
		'Strzebiñ',
		'Strzy¿owice',
		'Studzionka',
		'Suszec',
		'Syrynia',
		'Szczekociny',
		'Szczyrk',
		'¦lemieñ',
		'¦wierklaniec',
		'¦wierklany Górne',
		'¦wiêtoch³owice',
		'¦wiêtoszówka',
		'¦winna',
		'Tarnowskie Góry',
		'T±pkowice',
		'Toszek',
		'Truskolasy',
		'Turza ¦l±ska',
		'Tworków',
		'Tworóg',
		'Tychy',
		'Ujso³y',
		'Ustroñ',
		'Waleñczów',
		'Warszowice',
		'Wêgierska Górka',
		'Wêglowice',
		'Wielowie¶',
		'Wieszowa',
		'Wilamowice',
		'Wilcza',
		'Wilkowice',
		'Wis³a',
		'Wis³a Wielka',
		'W³odowice',
		'Wodzis³aw ¦l±ski',
		'Wojkowice',
		'Wojkowice Ko¶cielne',
		'Wola',
		'Wo¼niki',
		'Wrêczyca Wielka',
		'Wrzosowa',
		'Wyry',
		'Zabrze',
		'Zabrzeg',
		'Zawiercie',
		'Zbros³awice',
		'Zebrzydowice',
		'Ziemiêcice',
		'Zwardoñ',
		'¯arki',
		'¯arki-Letnisko',
		'¯arnowiec',
		'¯ernica',
		'¯ory',
		'¯ywiec'
	);
	$swietokrzyskie = array(
		'swietokrzyskie',
		'Kielce',
		'Baækowice',
		'Ba³tów',
		'Bejsce',
		'Bieliny',
		'Bli¿yn',
		'Bodzechów',
		'Bodzentyn',
		'Bogoria',
		'Brody',
		'Busko-Zdrój',
		'Chêciny',
		'Chmielnik',
		'Czarnocin',
		'Æmielów',
		'Daleszyce',
		'Dwikozy',
		'Dzia³oszyce',
		'Fa³ków',
		'Gnojno',
		'Gowarczów',
		'Górno',
		'Imielno',
		'Iwaniska',
		'Jêdrzejów',
		'Kazimierza Wielka',
		'Kije',
		'Klimontów',
		'Kluczewsko',
		'Koñskie',
		'Koprzywnica',
		'Krasocin',
		'Kunów',
		'Lipnik',
		'£agów',
		'£±czna',
		'£oniów',
		'£opuszno',
		'£ubnice',
		'Ma³ogoszcz',
		'Mas³ów',
		'Micha³ow k. Piñczowa',
		'Miedziana Góra',
		'Mirzec',
		'Mniów',
		'Morawica',
		'Moskorzew',
		'Nag³owice',
		'Nowa S³upia',
		'Nowy Korczyn',
		'Obrazów',
		'Oksa',
		'Ole¶nica',
		'Opatowiec',
		'Opatów',
		'Osiek',
		'Ostrowiec ¦wiêtokrzyski',
		'O¿arów',
		'Pacanów',
		'Paw³ów',
		'Piekoszów',
		'Pierzchnica',
		'Piñczów',
		'Po³aniec',
		'Radków',
		'Radoszyce',
		'Raków',
		'Ruda Maleniecka',
		'Rytwiany',
		'Sadowie',
		'Samborzec',
		'Sandomierz',
		'Secemin',
		'Sêdziszów',
		'Sitkówka',
		'Skalbmierz',
		'Skar¿ysko Ko¶cielne',
		'Skar¿ysko-Kamienna',
		'S³upia',
		'S³upia',
		'Smyków',
		'Sobków',
		'Solec-Zdrój',
		'Starachowice',
		'Staszów',
		'St±porków',
		'Stopnica',
		'Strawczyn',
		'Suchedniów',
		'Szyd³ów',
		'Tar³ów',
		'Tuczêpy',
		'Wa¶niów',
		'W±chock',
		'Wi±zownica',
		'Wilczyce',
		'Wi¶lica',
		'W³ostów',
		'W³oszczowa',
		'Wodzis³aw',
		'Wojciechowice',
		'Zagnañsk',
		'Zawichost',
		'Z³ota'
	);
	$warminskomazurskie = array(
		'warminskomazurskie',
		'Olsztyn',
		'Banie Mazurskie',
		'Baranowo',
		'Barciany',
		'Barczewo',
		'Bartoszyce',
		'Bemowo Piskie',
		'Bezledy',
		'Bia³a Piska',
		'Biskupiec',
		'Biskupiec k. I³awy',
		'Bisztynek',
		'Braniewo',
		'Budry',
		'Butryny',
		'D±brówno',
		'Dobre Miasto',
		'Dryga³y',
		'Dubeninki',
		'Dywity',
		'Dzia³dowo',
		'D¼wierzuty',
		'Elbl±g',
		'E³k',
		'Frombork',
		'Galiny',
		'Gierzwa³d',
		'Gietrzwa³d',
		'Gi¿ycko',
		'Godkowo k. Pas³êka',
		'Go³dap',
		'Górowo I³aweckie',
		'Grabowo',
		'Grodziczno',
		'Gronowo Elbl±skie',
		'Gródki',
		'Grunwald',
		'I³awa',
		'I³owo',
		'Jamielnik',
		'Janowiec Ko¶cielny',
		'Janowo',
		'Jedwabno',
		'Jeg³ownik',
		'Jerzwa³d',
		'Jeziorany',
		'Jonkowo',
		'Kalinowo',
		'Kamiñsk',
		'Karolewo',
		'Karwica',
		'Kêtrzyn',
		'Kisielice',
		'Kiwity',
		'Klebark Wielki',
		'Kolno',
		'Korsze',
		'Kowale Oleckie',
		'Koz³owo',
		'Kraszewo',
		'Krotoszyny Pomorskie',
		'Kruklanki',
		'Krutyñ',
		'Kurzêtnik',
		'Lelkowo',
		'Lidzbark k. Dzia³dowa',
		'Lidzbark Warmiñski',
		'Lipowiec',
		'Lipowina',
		'Lubawa',
		'Lubomino',
		'£abêdnik',
		'£±korz',
		'£ukta',
		'Ma³dyty',
		'Markusy',
		'Marzêcice k. Nowego Miasta Lubawskiego',
		'Miko³ajki',
		'Milejewo',
		'Mi³akowo',
		'Mi³ki',
		'Mi³om³yn',
		'M³ynary',
		'Mo³tajny',
		'Mor±g',
		'Mr±gowo',
		'Mroczno',
		'Nakomiady',
		'Napiwoda',
		'Nidzica',
		'Nowa Wie¶ E³cka',
		'Nowe Miasto Lubawskie',
		'Olecko',
		'Olsztynek',
		'Olszyny',
		'Orneta',
		'Orzysz',
		'Ostróda',
		'Pas³êk',
		'Pasym',
		'Piecki',
		'Pieniê¿no',
		'Pisanica',
		'Pisz',
		'P³oskinia',
		'P³o¶nica',
		'Pozezdrze',
		'Prostki',
		'Purda',
		'Radomno',
		'Reszel',
		'Rodnowo',
		'Rogó¿',
		'Rozogi',
		'Ro¿ental',
		'Ruciane-Nida',
		'Rudzienice',
		'Runowo',
		'Rybno',
		'Rybno',
		'Rychliki',
		'Ryn',
		'S±topy-Samulewo',
		'Sêpopol',
		'Siemiany',
		'Sorkwity',
		'Spychowo',
		'Srokowo',
		'Stare D³utowo',
		'Stare Jab³onki',
		'Stare Juchy',
		'Stawiguda',
		'Susz',
		'Szczechy Wielkie',
		'Szczytno',
		'Szyldak',
		'¦wi±tki',
		'¦wiêtajno',
		'¦wiêtajno',
		'Tereszewo',
		'Tolkmicko',
		'Ukta',
		'Uzdowo',
		'Wêgorzewo',
		'Wiartel',
		'Wielbark',
		'Wieliczki',
		'Wilczêta',
		'Wilkasy',
		'Wojciechy',
		'Wydminy',
		'Zagaje',
		'Zalewo',
		'Z±browo',
		'Zielonka Pas³êcka',
		'¯elazna Góra'
	);
	$wielkopolskie = array(
		'wielkopolskie',
		'Poznañ',
		'Babiak',
		'Bia³o¶liwie',
		'Biedrusko',
		'Biskupice',
		'Biskupice k. Pobiedzisk',
		'Blizanów',
		'Bojanowo',
		'Bolewice',
		'Borek',
		'Borek Wielkopolski',
		'Borek Wlkp.',
		'Bralin',
		'Brodnica',
		'Brudzew',
		'Brzeziny',
		'Budzis³aw Ko¶cielny',
		'Budzyñ',
		'Buk',
		'Ceków',
		'Che³st',
		'Chludowo',
		'Chocz',
		'Chodów',
		'Chodzie¿',
		'Chrzypsko Wielkie',
		'Czajków',
		'Czarnków',
		'Czempiñ',
		'Czermin',
		'Czerniejewo',
		'Czerwonak',
		'Damas³awek',
		'D±bie',
		'Dobra',
		'Dobroso³owo',
		'Dobrzyca',
		'Dolsk',
		'Dopiewo',
		'Doruchów',
		'Drawski M³yn',
		'Drawsko',
		'Duszniki',
		'Duszniki Wielkopolskie',
		'Duszniki Wlkp.',
		'Dzia³yñ',
		'Fa³kowo',
		'G±dki',
		'Giza³ki',
		'Gniezno',
		'Godziesze Ma³e',
		'Golina',
		'Go³añcz',
		'Go³uchów',
		'Gostyñ',
		'Grabów nad Prosn±',
		'Grabów n. Prosn±',
		'Granowo',
		'Grochowy',
		'Grodziec',
		'Grodzisk',
		'Grodzisk Wielkopolski',
		'Grodzisk Wlkp.',
		'Grzegorzew',
		'Jaraczewo',
		'Jarocin',
		'Jarz±bkowo',
		'Jastrowie',
		'Jutrosin',
		'Kaczory',
		'Kalisz',
		'Kamieniec',
		'Kawêczyn',
		'Kazimierz Biskupi',
		'Ka¼mierz',
		'Ka¼mierz k. Poznania',
		'Ka¼mierz ko³o Poznania',
		'Kêpno',
		'Kiszkowo',
		'Kleczew',
		'Kleszczewo Poznañskie',
		'K³ecko',
		'K³odawa',
		'Kobierno',
		'Kobyla Góra',
		'Kobylin',
		'Ko¼min',
		'Ko¼min Wielkopolski',
		'Ko¼min Wlkp.',
		'Kobylnica k. Poznania',
		'Ko³aczkowo k. Wrze¶ni',
		'Ko³o',
		'Komorniki',
		'Konin',
		'Korzeniew',
		'Kostrzyn',
		'Kostrzyn Wielkopolski',
		'Kostrzyn Wlkp.',
		'Ko¶cian',
		'Ko¶cielec',
		'Kotlin',
		'Kowalew',
		'Kozieg³owy',
		'Kozieg³owy k. Poznania',
		'Ko¼min',
		'Ko¼min Wielkopolski',
		'Ko¼min Wlkp.',
		'Ko¼minek',
		'Kórnik',
		'Krajenka',
		'Kramsk',
		'Kraszewice',
		'Krobia',
		'Krotoszyn',
		'Krzemieniewo',
		'Krzykosy',
		'Krzykosy k. ¦rody Wielkopolskiej',
		'Krzymów',
		'Krzywiñ',
		'Krzy¿',
		'Krzy¿ Wielkopolski',
		'Krzy¿ Wlkp.',
		'Ksi±¿ Wielkopolski',
		'Ksi±¿ Wlkp.',
		'Kuchary Ko¶cielne',
		'Ku¶lin',
		'Kwilcz',
		'L±dek',
		'Leszno',
		'Lipka k. Z³otowa',
		'Lipno',
		'Lisków',
		'Lotyñ',
		'Lubasz',
		'Luboñ',
		'Lwówek',
		'Lwówek k. Nowego Tomy¶la',
		'£ekno',
		'£êka Ma³a',
		'£êka Opatowska',
		'£ob¿enica',
		'£owyñ',
		'£ubowo',
		'£ubowo k. Gniezna',
		'Malanów',
		'Margonin',
		'Miasteczko Krajeñskie',
		'Miedzichowo',
		'Miejska Górka',
		'Mieleszyn',
		'Mieleszyn k. Gniezna',
		'Mie¶cisko',
		'Miêdzychód',
		'Mikstat',
		'Mi³os³aw',
		'Mosina',
		'Mroczeñ',
		'Murowana Go¶lina',
		'Murzynowo Ko¶cielne',
		'Nekla',
		'Niechanowo',
		'Nowe Miasto',
		'Nowe Miasto n. Wart±',
		'Nowe Skalmierzyce',
		'Nowy Tomy¶l',
		'Oborniki',
		'Oborniki k. Poznania',
		'Obra',
		'Obrzycko',
		'Odolanów',
		'Okonek',
		'Olszówka',
		'Opalenica',
		'Opatówek',
		'Orchowo',
		'Orzechowo',
		'Osieczna',
		'Osiek Ma³y',
		'Osiek',
		'Osiek n. Noteci±',
		'Ostroróg',
		'Ostrowite',
		'Ostrów',
		'Ostrów Wlkp.',
		'Ostrów Wielkopolski',
		'Ostrzeszów',
		'Owiñska',
		'Pakos³aw',
		'Perzów',
		'Pêpowo',
		'Piaski',
		'Pi³a',
		'Pleszew',
		'Plewiska',
		'Pniewy',
		'Pobiedziska',
		'Pogorzela',
		'Po³ajewo',
		'Poniec',
		'Popowo Ko¶cielne',
		'Popówko',
		'Powidz',
		'Przedecz',
		'Przemêt',
		'Prze¼mierowo',
		'Przygodzice',
		'Przykona',
		'Pudliszki',
		'Puszczykowo',
		'Pyzdry',
		'Rakoniewice',
		'Raszków',
		'Rawicz',
		'Rogo¼no',
		'Rogo¼no Wielkopolskie',
		'Rokietnica',
		'Rokietnica k. Poznania',
		'Rozdra¿ew',
		'Rychtal',
		'Rychwa³',
		'Ryczywó³',
		'Rydzyna',
		'Sieraków',
		'Rzgów',
		'Sadlno',
		'Siedlec',
		'Sieraków',
		'Sieraków Wielkopolski',
		'Sieroszewice',
		'Skoki',
		'Skorzêcin',
		'Skulsk',
		'S³upca',
		'S³upia',
		'S³upia pod Kêpnem',
		'Sobótka',
		'Sokolniki',
		'Sokolniki k. Wrze¶ni',
		'Sompolno',
		'So¶nie',
		'Stare Miasto',
		'Stary Licheñ',
		'Stawiszyn',
		'Stêszew',
		'Strza³kowo',
		'Suchy Las',
		'Sulmierzyce',
		'Swarzêdz',
		'Szamocin',
		'Szamotu³y',
		'Szczytniki',
		'Szyd³owo',
		'¦lesin',
		'¦migiel',
		'¦rem',
		'¦roda',
		'¦roda Wielkopolska',
		'¦roda Wlkp.',
		'¦wiêciechowa',
		'Tarnowo Podgórne',
		'Tarnówka',
		'Trzcianka',
		'Trzcianka Lubuska',
		'Trzcinica',
		'Trzemeszno',
		'Tulce',
		'Tuliszków',
		'Turek',
		'Uj¶cie',
		'Wapno',
		'W±growiec',
		'Wieleñ',
		'Wielichowo',
		'Wijewo',
		'Wilczyn',
		'Witaszyce',
		'Witkowo',
		'Witowo',
		'Witowo k. ¦rody Wielkopolskiej',
		'W³adys³awów',
		'W³oszakowice',
		'Wolsztyn',
		'Wronki',
		'Wrze¶nia',
		'Wyrzysk',
		'Wysoka',
		'Zagórów',
		'Zakrzewo',
		'Zaniemy¶l',
		'Zaryñ',
		'Zb±szyñ',
		'Zbiersk',
		'Zduny',
		'Z³otów',
		'¯elazków',
		'¯erków',
		'¯ydowo',
		'¯ydowo k. Gniezna'
	);
	$zachodniopomorskie = array(
		'zachodniopomorskie',
		'Szczecin',
		'Banie',
		'Barlinek',
		'Barwice',
		'Barzkowice',
		'Bêdzino',
		'Bia³ogard',
		'Bia³y Bór',
		'Bielice',
		'Bierzwnik',
		'Biesiekierz',
		'Bobolice',
		'Boleszkowice',
		'Bonin',
		'Borne Sulinowo',
		'Broczyno',
		'Brojce Gryfickie',
		'Brzesko',
		'Brze¿no',
		'Cedynia',
		'Cerkwica',
		'Charzyno',
		'Chociwel',
		'Chojna Szczeciñska',
		'Choszczno',
		'Cychry',
		'Czaplinek',
		'Czarnog³owy',
		'Cz³opa',
		'Dar³owo',
		'D±bki k. Koszalina',
		'Dêbno Lubuskie',
		'Dêbo³êka',
		'Dobra',
		'Dobra',
		'Dobrowo k. Bia³ogardu',
		'Dobrzany',
		'Dobrzyca',
		'Dolice',
		'Do³uje',
		'Drawno',
		'Drawsko Pomorskie',
		'Drzonowo',
		'Drzonowo',
		'Dygowo',
		'Dziwnów',
		'D¼wirzyno',
		'Golczewo',
		'Golenice',
		'Goleniów',
		'Gorawino',
		'Go¶cino',
		'Gryfice',
		'Gryfino',
		'Grzmi±ca',
		'Grzybowo',
		'Gwda Wielka',
		'Iñsko',
		'Jaros³awiec',
		'Kalisz Pomorski',
		'Kamieñ Pomorski',
		'Karlino',
		'Karnice',
		'Karsibór',
		'Karsko',
		'Kliniska',
		'Kluczewo',
		'Kobylanka',
		'Ko³baskowo',
		'Ko³czewo',
		'Ko³obrzeg',
		'Koszalin',
		'Kozielice',
		'Krzêcin',
		'Krzywin',
		'Lekowo',
		'Lipiany',
		'Lubanowo',
		'Lubczyna',
		'Lubiesz',
		'£adzin',
		'£azy',
		'£±cko',
		'£obez',
		'£o¿nica',
		'£ubowo',
		'£ukêcin',
		'Malechowo',
		'Manowo',
		'Marianowo',
		'Maszewo',
		'Mielêcin',
		'Mielno',
		'Mieszkowice',
		'Miêdzywodzie',
		'Miêdzyzdroje',
		'Miros³awiec',
		'Moryñ',
		'Mostkowo',
		'Mosty',
		'Mrze¿yno Gryfickie',
		'M¶cice',
		'My¶libórz',
		'Nac³aw',
		'Namy¶lin',
		'Nawodna',
		'Niechorze',
		'Nowe Czarnowo',
		'Nowe Warpno',
		'Nowe Worowo',
		'Nowogard',
		'Nowogródek Pomorski',
		'Oleszno',
		'Osina',
		'Ostrowice',
		'Ostrowiec S³awieñski',
		'Parsêcko',
		'Pe³czyce',
		'Pêzino',
		'P³otno',
		'P³oty',
		'Pobierowo',
		'Pogorzelica k. Gryfic',
		'Polanów',
		'Police',
		'Polne',
		'Po³czyn Zdrój',
		'Popielewo',
		'Postomino',
		'Przec³aw',
		'Przelewice',
		'Przybiernów',
		'Pustkowo',
		'Pyrzyce',
		'Radowo Ma³e',
		'R±bino',
		'Recz',
		'Red³o',
		'Resko',
		'Rewal',
		'Rosnowo',
		'Ró¿añsko',
		'Ró¿ewo',
		'Rusinowo',
		'Rydzewo',
		'Rymañ',
		'Sarbinowo Morskie',
		'Sianów',
		'Siemy¶l',
		'Silnowo',
		'S³awno',
		'S³awoborze',
		'Stanomino',
		'Stara D±browa',
		'Stare Czarnowo',
		'Stargard Szczeciñski',
		'Stary Chwalim',
		'Stepnica',
		'Str±czno',
		'Sucha Koszaliñska',
		'Suchañ',
		'Suliszewo',
		'Szczecinek',
		'Szczecinek',
		'Szwecja',
		'¦widwin',
		'¦wierzno',
		'¦wieszyno',
		'¦winouj¶cie',
		'Tanowo',
		'Tetyñ',
		'Toporzyk',
		'Troszyn',
		'Trzciñsko-Zdrój',
		'Trzebiatów',
		'Trzebie¿',
		'Tuczno',
		'Turowo Pomorskie',
		'Tychowo',
		'Tymieñ',
		'Ustronie Morskie',
		'Wa³cz',
		'Warnice',
		'Wêgorzyno',
		'Wicimice',
		'Widuchowa',
		'Wierzchowo',
		'Wise³ka',
		'Wolin',
		'Wrze¶nica',
		'Wrzosowo k. Bia³ogardu',
		'Z³ocieniec',
		'¯arnowo Szczeciñskie',
		'¯ó³tnica',
		'¯ukowo',
		'¯ydowo'
	);

	$domena = $_GET['domena'];
	if (substr($domena, -1, 1) == '/') {
			$domena = substr($domena,0, (strlen($domena) - 1));
	}
	$fraza = $_GET['fraza'];
	$alias = $_GET['alias'];
	$ilosc = $_GET['ilosc'];
	if ($ilosc == '') { $ilosc = 5; } else $ilosc = (int)$ilosc;
	$templatka = $_GET['templatka'];
	$htaccess = $_GET['htaccess'];
	$zamiana = $_GET['zamiana'];
	$link = str_replace('{fraza}', $fraza, str_replace('&#8243;', '"', $_GET['link']));
	$zip = new ZipArchive();
	$zip->open('paczka.zip', ZipArchive::OVERWRITE);
	$zip->addFromString('.htaccess', $htaccess);
	$file = 'sprzeg.php';
	$fp = fopen($file, rb);
	$sprzeg = fread($fp, filesize($file));
	fclose($fp);
	$sprzeg = str_replace('{domena}', $domena, $sprzeg);
	$sprzeg = str_replace('{fraza}', $fraza, $sprzeg);
	$sprzeg = str_replace('{alias}', $alias, $sprzeg);
	$sprzeg = str_replace('{ilosc}', $ilosc, $sprzeg);
	$sprzeg = str_replace('{templatka}', $templatka, $sprzeg);
	$sprzeg = str_replace('{link_tmp}', $link, $sprzeg);
	$sprzeg = str_replace('{zamiana}', $zamiana, $sprzeg);
	$zip->addFromString('sprzeg.php', $sprzeg);
	for ($j = 0; $j < count($wojewodztwa); $j++) {
		for ($i = 1; $i < count(${$wojewodztwa[$j]}); $i++) {
			$plik = $alias . "_" . ${$wojewodztwa[$j]}[0] . "_" . urlencode(strtolower(strtr(${$wojewodztwa[$j]}[$i],'¡ÆÊ£ÑÓ¦¯¬±æê³ñó¶¿¼.','ACELNOSZZacelnoszzk'))) . ".php";
			$mapa[] = $domena . '/' . $plik;
		}
	}
	$zapis = '<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

<url>
<loc>http://' . $domena . '/</loc>
<lastmod>' . date("Y-m-d") . '</lastmod>
<priority>1.0</priority>
</url>
';
	for ($i = 0; $i < count($mapa); $i++) {
		$zapis .=  '<url>
<loc>http://' . $mapa[$i] . '</loc>
<lastmod>' . date("Y-m-d") . '</lastmod>
<priority>0.' . rand(5, 9) . '</priority>
</url>
';
	}
	$zapis .= '
</urlset>';

	$fp1 = gzopen('sitemap.xml.gz','wb');
	gzwrite($fp1, $zapis);
	gzclose($fp1);
	$zip->addFile('sitemap.xml.gz');
	$zapis = '<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://www.google.com/webmasters/tools/ping?sitemap=http%3A%2F%2F' . $domena . '%2Fsitemap.xml.gz");
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_exec($ch);
curl_close($ch);
$bi = curl_init();
curl_setopt($bi, CURLOPT_URL, "http://www.bing.com/webmaster/ping.aspx?siteMap=http%3A%2F%2F' . $domena . '%2Fsitemap.xml.gz");
curl_setopt($bi, CURLOPT_HEADER, 0);
curl_exec($bi);
curl_close($bi);
?>';
	$zip->addFromString('ping.php', $zapis);
	$zip->close();
	header("Location: mgenerator.php?kontrolka=comamzrobic&domena=" . $domena);
}
?>